### ISSUE TITLE
Is it possible to use the Delta encodings?

### ISSUE THREAD

**Issue by Bio2hazard** [G-Research/ParquetSharp#113]
Hi,

I wanted to experiment with the delta encodings to see if they offer any advantage over the RleDictionary encoding that it seems to use on everything by default.

I am creating a `WriterPropertiesBuilder` and set `.Version(ParquetVersion.PARQUET_2_0)`.

Then, I disable the dictionary and set the appropriate encoding. In this case, `node.Name` is "Time", which is a  `INT64` Timestamp and I wanted to try the `DeltaBinaryPacked` encoding.

```
builder.DisableDictionary(node.Name);
builder.Encoding(node.Name, ParquetSharp.Encoding.DeltaBinaryPacked);
```

This results in a `ParquetException`: `class parquet::ParquetException (message: 'Not yet implemented: Selected encoding is not supported.')`

This seems to come from here: https://github.com/apache/parquet-cpp/blob/80e110c823c5631ce4a4f0a5da486e759219f1e3/src/parquet/column_writer.cc#L552

Is there a way around this, or is it just a limitation of the underlying c++ implementation?

**Comment by GPSnoopy** [comment]
Hi,

According to this archived post, delta encoding is only supported on the read path but not write path. 
http://mail-archives.apache.org/mod_mbox/arrow-dev/201811.mbox/%3CCAJPUwMArwcO_wf2rVfqOkSxDfba9G-2KCSdyBkjfH=cY+=X3Qg@mail.gmail.com%3E

Last time I heard from the Arrow project, they did not recommend using the Parquet 2.0 format, as it's not currently well supported (as you have yourself noticed). 

Regards,
Tanguy

**Comment by GKrivosheev-rms** [comment]
Aa a followup, are there any alternatives to Delta available in ParquetSharp for efficient encoding of incrementing numbers such as 
 columnX: {1,2,3,4,5....}

**Comment by GPSnoopy** [comment]
@GKrivosheev-rms I'd recommend trying a few encodings and compressions on your data to specifically answer that question.

I would try Plain, RLE and/or Dictionary Encoding crossed with Snappy, Lz4, Zstd, or Brotli Compression.

Also if you are encoding Floats/Doubles, I recommend looking at [Byte Stream Split](https://github.com/apache/parquet-format/blob/master/Encodings.md#byte-stream-split-byte_stream_split--9) encoding.

**Comment by GKrivosheev-rms** [comment]
So far I tried Dictionary and RLE with poor results.  Because numbers change slightly between rows, I'd expect delta to help in this scenario...

**Comment by GPSnoopy** [comment]
I'm more curious about the impact of compression. I wouldn't underestimate it; will have more impact than the encoding.

**Comment by GPSnoopy** [comment]
Closing since there is not much ParquetSharp can do here; solely in upstream land. And it does not look like upstream wants to do it (IIUC they consider delta encoding to be obsolete - deprecated). If a new version of Arrow comes that supports it, we'll support it too and add the proper enums for it.
