### ISSUE TITLE
Writing buffered row groups with plain encoding leads to corrupt data.

### ISSUE THREAD

**Issue by GPSnoopy** [G-Research/ParquetSharp#116]
See buffered unit tests in TestPhysicalTypeRoundTrip.
(current in branch https://github.com/G-Research/ParquetSharp/tree/BufferedRowGroupTest)

It appears that an upstream bug recently introduced (Arrow 0.16) causes file/data corruption when writing a large number of rows using buffered row groups and plain encoding.

The problem does not seem to happen if any of the following is true:
- using normal unbuffered row groups,
- using dictionary encoding,
- writing a small number of rows (less than ~50K, ballpark figure).

There also seem to be a smaller unrelated issue, where the list of returned Encodings from the column chunk metadata contains duplicated entries (Plain encoding in these tests).

Attempt at investigating and fixing the upstream issue here:
https://github.com/G-Research/gr-oss/issues/136

**Comment by tpboudreau** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-8127 . I'll submit a PR against it on Monday.

**Comment by tpboudreau** [comment]
https://github.com/apache/arrow/pull/6637

**Comment by GPSnoopy** [comment]
Fixed in 2.2.0-beta1.
