### ISSUE TITLE
Memory pressure and perforamnce on string heavy parquet

### ISSUE THREAD

**Issue by SpencerBullent** [G-Research/ParquetSharp#118]
I have noticed some extreme memory pressure and performance issues when working with string heavy parquet. Looking at the column reader it UTF8 decodes every string instance. Perhaps a better strategy would be to keep a instance cache ` ByteArray -> String`?

**Comment by GPSnoopy** [comment]
PR #119 shoud alleviate this problem.

It tracks the presence of dictionary encoding and assumes it's a good proxy for choosing whether to cache duplicate `ByteArray` entries or not. This is currently only enabled for `string` as they are immutable. But the same logic can easily be applied to `byte[]` (probably behind an optional flag, as they are not immutable and could confuse the user if he modifies these arrays).

**Comment by GPSnoopy** [comment]
Released in 2.2.0-beta1.
