### ISSUE TITLE
Add UUID support

### ISSUE THREAD

**Issue by blazem-msft** [G-Research/ParquetSharp#139]
ParquetSharp has already consumed an Arrow version supporting the UUID logical type, but there's no support for it in ParquetSharp yet, i.e. in ColumnDescriptor.cs

**Comment by GPSnoopy** [comment]
I've mapped C# `Guid` to Parquet `UUID` logical type in PR #141. Should be merged to master soon.

**Comment by GPSnoopy** [comment]
Released as part of 2.2.0-beta4.
