### ISSUE TITLE
Writing sparse Decimals and DateTimes

### ISSUE THREAD

**Issue by pkese** [G-Research/ParquetSharp#147]
I'm having trouble trying to find my way around writing sparse larger binary types.

I having an `Array<DateTime>` or `Array<Decimals>` with an accompanying array of `defLevels`.

I keep getting:  
`Unhandled exception. System.InvalidCastException: Unable to cast object of type 'ParquetSharp.ColumnWriter'1[System.Int64]' to type 'ParquetSharp.ColumnWriter'1[System.DateTime]'`

when trying to write with `WriteBatch(nItems, defLevels, null, dates: Array<DateTime>)`.

What am I doing wrong?

**Comment by pkese** [comment]
... similarly with Decimals:  
`Unhandled exception. System.InvalidCastException: Unable to cast object of type 'ParquetSharp.ColumnWriter'1[ParquetSharp.FixedLenByteArray]' to type 'ParquetSharp.ColumnWriter'1[System.Decimal]`

**Comment by pkese** [comment]
If I convert data into System.Nullable<Decimal>, then the app terminates in the middle of writing  
(without any exceptions, but returning system exit code 139).

**Comment by GPSnoopy** [comment]
Hi @pkese,

When you use `ColumnWriter` directly, only the Parquet physical types are supported. On top of that you have to provide explicit definition and repetition levels. See the following for a list of supported physical types.

https://github.com/G-Research/ParquetSharp/blob/d0edafb2f9aded9c8407fc9369baea7a48440607/cpp/TypedColumnWriter.cpp#L49-L56

If you can, I would suggest you use `LogicalColumnWriter` instead (as per example in the README) as this will do the logical type conversion for you as well as (hopefully) the correct definition and repetition levels. Figuring out the right values for the latter is quite tricky (see `WriteArray` in `LogicalColumnWriter.cs` as a starting point and be prepared for some headaches).

Using `LogicalColumnWriter` you'll have to choice between `DateTime[]` and `DateTime?[]` depending on whether you want to support optional (i.e. nullable) entries in the list. ParquetSharp considers the array itself to always be nullable (as to match C# `Array`).

Hope this helps

**Comment by pkese** [comment]
Thanks for your quick response.

So I switched to LogicalColumnWriter for these types.

It turned out that my problem was:  
When I was using `ColumnWriter` directly, and when there was `defLevels` supplied (i.e. not all values were populated),  
I had to specify my column definitions as `Column<Nullable<T>>(name)` instead of `Column<T>(name)`.
