### ISSUE TITLE
Support to RowGroup::sort_columns

### ISSUE THREAD

**Issue by FerHenrique** [G-Research/ParquetSharp#163]
Parquet format supports the definition of a set of columns to describe the columns used to sort order of data in a row group. 

This set of columns is called "sorting_columns", and it's defined in the parquet-format project containing format specifications and Thrift definitions of metadata required to properly read Parquet files. A link to this definition can be found here: https://github.com/apache/parquet-format/blob/01971a532e20ff8e5eba9d440289bfb753f0cf0b/src/main/thrift/parquet.thrift#L818

I see that in ParquetSharp, that RowGroupWriter has a quite similar structure to parquet-format::RowGroup. But it does not contain "sorting_columns". Is correct to affirm that they are equivalent? If yes, then is there any plan to add support to this structure of columns?

I also noticed that ColumnDescriptor class contains a property called SortOrder, which differs from parquet-format::SortingColumn (been just a enum). Can ColumnDescriptor.SortOrder be used as an alternative to describe the columns sorting data in the RowGroup? 
I was not able to find in parquet-format::ColumnMetaData a property that similar to SortOrder, for this reason I have the impression that sorting columns definition (originally specified in parquet-format::RowGroup) is defined in ColumnDescriptor.

**Comment by GPSnoopy** [comment]
Hi @FerHenrique ,

IIRC `ColumnDescriptor.SortOrder` is only for the statistic properties (e.g. min/max).

Looking around, I've found this ticket in Apache Arrow/Parquet: https://issues.apache.org/jira/browse/PARQUET-1881. It looks like the `SortingColumns` feature from Parquet Format is not supported in either the Apache Java implementation nor the Apache Arrow C++ implementation. Or did I miss something?

Are you able to use this in another library?

**Comment by FerHenrique** [comment]
Yes, I had the same impression looking in the other repos.
I looks to me that nobody is supporting it, but the original Parquet-Format spec has it. 

Is there a correct procedure following that? 
I understand that at least the Apache Arrow C++ implementation should support it, to make ParquetSharp's implementation easier.

**Comment by GPSnoopy** [comment]
I guess you can always raise a query on https://issues.apache.org/jira/projects/PARQUET (look if there isn't one already).
