### ISSUE TITLE
Provide a utility method to reverse map from the 'original' column name to the column index. 

### ISSUE THREAD

**Issue by UncleMattHope** [G-Research/ParquetSharp#176]
Naive use of something like: ```reader.FileMetaData.Schema.ColumnIndex("name")``` does not work based on the names provided when originally adding columns except for trivial instance where no Dremel shredding was needed.
As an example, for adding a List type column via something like:
```
writer = new ParquetFileWriter(
    "example.parquet", 
    new Column<double[]>("values")),
    new WriterPropertiesBuilder().Build());
```

Will result in it being shredded into "values.list.item". The resulting name of the node which is dierctly associated with this column is then "item". Lookup via a ColumnPath of "values.list.item" would work, but I believe this is confusing to the end user of the API. They specified a column with a name "values", they would expect that asking for the index of a column called "values" would return the right index, not fail.

Here is a work around that works for the simple list columns. I haven't verified it against anything more complex

```
public static string GetColumnIndexFromName(ParquetFileReader reader, string name)
{
    foreach (var i in Enumerable.Range(0, reader.FileMetaData.Schema.NumColumns))
    {
        var column = _reader.FileMetaData.Schema.Column(i);
        var node = column.SchemaNode;
        while (node.Parent.FieldId != 0)
        {
            node = node.Parent;
        }
        if (node.Name == name)
        {
            return i;
        }
   }
   throw new KeyNotFoundException($"Failed to find column {name}");
}
```

**Comment by GPSnoopy** [comment]
After merging PR #181 (see unit tests), there are at least two confirmed ways of getting the column root name:

```c#
fileReader.FileMetaData.Schema.ColumnRoot(c).Name; // Use schema info for column at index c.
columnReader.ColumnDescriptor.Path.ToDotVector().First(); // Use column path from column descriptor.
```

This should simplify the loop above.

**Comment by GPSnoopy** [comment]
There is also `fileMetaData.Schema.ColumnIndex(path)` but that requires knowing the full path of the column, not just the name of the parent node.
