### ISSUE TITLE
Processor architecture error when using F# Interactive

### ISSUE THREAD

**Issue by markpattison** [G-Research/ParquetSharp#197]
While I can happily use ParquetSharp from a compiled project, I can't get it to work from FSI.

I'm using the version of FSI that comes with VS2019 16.9.5, `F# Interactive version 11.3.2.0 for F# 5.0`, which I open by running `fsi` from a VS2019 Developer Command Prompt.  I'm using Windows 10.

As shown below, I get a warning when referencing the package, and an error when trying to use it:
```
> #r "nuget: ParquetSharp, 2.4.0";;
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "C:\Users\mpattison\.nuget\packages\parquetsharp\2.4.0\lib\net461\ParquetSharp.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\Users\mpattison\AppData\Local\Temp\nuget\5112--af6c479e-68e2-4f25-9512-8d5ddadb370c\Project.fsproj]
[Loading C:\Users\mpattison\AppData\Local\Temp\nuget\5112--af6c479e-68e2-4f25-9512-8d5ddadb370c\Project.fsproj.fsx]
namespace FSI_0002.Project

> let c = ParquetSharp.Column<int>("c");;


error FS0193: internal error: Could not load file or assembly 'ParquetSharp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```
Strangely, it works fine when running the same code from FSI within Visual Studio (e.g. selecting the code and hitting Alt-Enter), even though that appears to be the same version of FSI.

**Comment by GPSnoopy** [comment]
Hi @markpattison,

It sounds like FSI is being run in 32bit instead of 64bit. ParquetSharp only works in x64, there are no x86 runtimes.

This might help (haven't tried, just did a quick search on Google):
https://stackoverflow.com/questions/4284381/how-to-run-fsi-exe-in-64-bits

**Comment by GPSnoopy** [comment]
This worked for me (Task Manager shows the process as being run in 64bit):

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>where fsianycpu
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsiAnyCpu.exe
```

Could you confirm whether that fixes your problem?

**Comment by markpattison** [comment]
Using `fsiAnyCpu.exe` did fix it, thank you very much.

For reference, it also works fine from `dotnet fsi` which presumably uses the 64-bit version as well.

I've suggested a short addition to the readme - entirely up to you if you want to include it!
