### ISSUE TITLE
LogicalType missing for Timestamp when isAdjustedToUtc is false

### ISSUE THREAD

**Issue by Nisden** [G-Research/ParquetSharp#216]
First off, I am not certain if this is an issue with ParquetSharp or the other Parquet implementations (Java and elastacloud/parquet-dotnet)

The issue is pretty simple, if I set `isAdjustedToUtc` to `false` when creating an Timestamp, other applications refuse to see the column as an Timestamp.

I have tested this hypothesise on:
  * Azure Synapse SQL On-Demand
  * [ParquetViewer](https://github.com/mukunku/ParquetViewer) uses [Parquet-dotnet](https://github.com/elastacloud/parquet-dotnet)
  * [Big data viewer](https://github.com/Eugene-Mark/bigdata-file-viewer) uses the java version of parquet-avro

My sample code is fairly simple
```
using (var fileStream = File.Open("sample.parquet", FileMode.Create))
            {
                using (var managedOutputStream = new ParquetSharp.IO.ManagedOutputStream(fileStream, leaveOpen: true))
                using (var file = new ParquetFileWriter(managedOutputStream, new Column[] {
                    new Column(typeof(DateTime), "DateUtcFalse", LogicalType.Timestamp(isAdjustedToUtc: false, TimeUnit.Millis)),
                    new Column(typeof(DateTime), "DateUtcTrue", LogicalType.Timestamp(true, TimeUnit.Millis))
                }))
                {
                    using (var rowGroup = file.AppendRowGroup())
                    {
                        for (int i = 0; i < 2; i++)
                        {
                            using (var columnWriter = rowGroup.NextColumn())
                            using (var logicalWriter = columnWriter.LogicalWriter<DateTime>())
                            {
                                logicalWriter.WriteBatch(new DateTime[]
                                {
                                    new DateTime(2000, 1, 1, 12, 00, 00),
                                    new DateTime(2021, 1, 1, 13, 30, 00),
                                    new DateTime(2023, 1, 1, 14, 30, 00)
                                });

                                columnWriter.Close();
                            }
                        }

                        rowGroup.Close();
                    }

                    file.Close();
                }
            }
```

**Comment by GPSnoopy** [comment]
This kind of behaviour would typically be dependent on the upstream implementation (i.e. Apache Arrow).

I suggest you try using PyArrow or Apache Arrow/Parquet C++to write an identical file and see if the portability problem still persist, or if the problem is contained within ParquetSharp.

Also note that Parquet .NET has been forked and is now maintained by https://github.com/aloneguid/parquet-dotnet. Worth trying if you can read your parquet file correctly with their latest version (maybe try this first).

**Comment by Nisden** [comment]
Ill give the other platform a try at a later date, but for now my workaround have simply been to not use `isAdjustedToUtc: false` as the application we use ignores it anyways.
