### ISSUE TITLE
Support for macOS - Arm64

### ISSUE THREAD

**Issue by Nisden** [G-Research/ParquetSharp#228]
Now with .NET 6 out, would it be possible to add native support for macOS Arm64 / M1 processors?

**Comment by jgiannuzzi** [comment]
Hi @Nisden, thanks a lot for your interest in ParquetSharp.

As ParquetSharp builds upon Arrow/Parquet C++ native code, we need to get this built too for Arm64. This may or may not involve some porting effort in Arrow, vcpkg, and ParquetSharp.

Once this is done, we might net yet be able to release an official NuGet, as the CI we use (GitHub Actions) does not have Arm64 runners yet (neither for macOS, nor for Linux). I believe this is tracked in https://github.com/actions/virtual-environments/issues/2187 (at least for macOS).

If you have access to a Mac with an Apple Silicon chip, you might want to try and build ParquetSharp on it and report the results. I would be very keen on knowing what the current status is!

**Comment by Nisden** [comment]
Thanks for the feedback. 

I should have reliable access to an M1 next month, so I can try compiling it then.
(Not that I can any great hopes, as I never really worked with C++)

**Comment by mfkl** [comment]
You can cross-compile from an Intel mac to target an Apple Silicon mac FYI https://stackoverflow.com/a/65385996/4064749. So building arm64 binaries in GitHub Action is possible (though you'd still need an M1 to run it).

**Comment by jgiannuzzi** [comment]
I have tried cross-compiling Arrow with vcpkg on an Intel Mac, but didn't get it working so far.

Looking at Apple Silicon offering in the cloud, I noticed that MacStadium has an open source program: https://www.macstadium.com/opensource. I will apply for it with ParquetSharp 🤞

**Comment by jgiannuzzi** [comment]
Update: I got the ParquetSharp tests running successfully on Linux ARM64. This is a good sign with regards to porting to Apple Silicon!

Here are the things I had to change to make it work:
- remove `arm64` from the unsupported architectures on [`ports/arrow/portfile.cmake` in Arrow](https://github.com/microsoft/vcpkg/blob/master/ports/arrow/portfile.cmake#L1)
- change the hardcoded triplet from `x64-linux` to `arm64-linux` in our [`build_unix.sh`](https://github.com/G-Research/ParquetSharp/blob/master/build_unix.sh#L7) and [`vcpkg_unix.sh`](https://github.com/G-Research/ParquetSharp/blob/master/vcpkg_unix.sh#L7) scripts
- remove `<Platforms>x64</Platforms>` and `<PlatformTarget>x64</PlatformTarget>` from our [various `csproj` files](https://github.com/G-Research/ParquetSharp/blob/master/csharp/ParquetSharp.csproj#L9-L10)

This is of course just a quick and dirty way to make it work, and we will need to discuss further the right way to go.

**Comment by jgiannuzzi** [comment]
Update: I also got the tests running successfully on a M1 Mac!

The same changes as above were required + a change to make them run under .NET 6 (previous versions have not been released for Apple Silicon):

* add `<RollForward>LatestMajor</RollForward>` to the [test project](https://github.com/G-Research/ParquetSharp/blob/master/csharp.test/ParquetSharp.Test.csproj)

**Comment by jgiannuzzi** [comment]
My PR to vcpkg to enable support for arm64 in Arrow has been merged: https://github.com/microsoft/vcpkg/pull/21467

**Comment by jgiannuzzi** [comment]
We will release ParquetSharp 5.0.0-beta3 with support for arm64 on macOS and Linux once #232 is merged

**Comment by jgiannuzzi** [comment]
[ParquetSharp 5.0.0-beta3](https://github.com/G-Research/ParquetSharp/releases/tag/5.0.0-beta3) has been released 🎉

**Comment by Nisden** [comment]
That's just awesome!
