### ISSUE TITLE
Read/Write C# DateTime as Int96

### ISSUE THREAD

**Issue by vikramrkin** [G-Research/ParquetSharp#235]
Hello G-Researchers,

I am trying to read/write C# DateTimes as legacy Int96 values using ParquetSharp. ParquetSharp is able to handle DateTime as Int64 easily but I cant find anything which reads/writes it as Int96. I have two questions on read/write:

1. Write operation:
I have tried:

```
//After creating this column, when trying to write a DateTime values, I get this exception:
//unsupported logical system type System.DateTime with logical type Timestamp(isAdjustedToUTC=true, timeUnit=nanoseconds, //is_from_converted_type=false, force_set_converted_type=false)
col = new Column(t, sanitizedColumnName, LogicalType.Timestamp(true, TimeUnit.Nanos));

```
and 

```
//This wrote the DateTime as Int64, not Int96
col = new Column(t, sanitizedColumnName, LogicalType.Timestamp(true, TimeUnit.Micros));
```

2. Read operation:
I generated a .parquet file with Int96 DateTime column in it (from another tool). When read, ParquetSharp gave ParquetSharp.Int96 field (not DateTime). Following the details from [this](https://stackoverflow.com/questions/66495650/converting-parquetsharp-int96-to-system-datetime), it still did not work.

I would appreciate if someone can shed some light on the two questions above.

Thanks
Vikram

**Comment by GPSnoopy** [comment]
Int96 is non-standard and should really be avoided at all cost. Its interpretation as a timestamp is nonstandard, depends on the application, and will not fit into a `DateTime`. Hence why ParquetSharp only allows you to read/write raw `Int96` and leaves it to the application to decide what is the correct behaviour. 

It's likely that the value you are trying to read are implemented using this logic: https://stackoverflow.com/questions/53103762/cast-int96-timestamp-from-parquet-to-golang/53104516#53104516

**Comment by vikramrkin** [comment]
Thanks for the clarification @GPSnoopy, appreciate it.
