### ISSUE TITLE
How can I use ParquetSharp from PowerShell?

### ISSUE THREAD

**Issue by dburtsev** [G-Research/ParquetSharp#239]
Hello
I would like to update some of my ETL scripts from csv to parquet.
1. How can I install ParquetSharp on the server without VS?
2. How can I reference ParquetSharp from the script (Import-Module / Add-Type -Assembly / [System.Reflection.Assembly]::LoadWithPartialName) ?
Thanks,
Dmitriy

**Comment by adamreeve** [comment]
Hi Dmitriy

ParquetSharp is available via NuGet so you can install the NuGet command line application and use that to install ParquetSharp, see the [NuGet command line docs here](https://docs.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference).

I tested using ParquetSharp from PowerShell and it is possible, one extra step that's needed is setting your Path environment variable so the native dll can be loaded. For example:
```powershell
# Install ParquetSharp into the current directory
nuget.exe install ParquetSharp

# Add native dll directory to Path
$nativeDllDir = Join-Path  (Get-Location) "ParquetSharp.4.0.0\runtimes\win-x64\native"
$env:Path += ";$nativeDllDir"

# Set current directory for .Net to match PowerShell
[Environment]::CurrentDirectory = (Get-Location).Path

# Load ParquetSharp
Add-Type -Path .\ParquetSharp.4.0.0\lib\net471\ParquetSharp.dll

# Create a ParquetFileReader
$reader = New-Object -TypeName ParquetSharp.ParquetFileReader -ArgumentList "./data.parquet"
```

I imagine trying to use the ParquetSharp API from PowerShell could get quite awkward though, you'd probably be better off writing an application in C# or F# that you could call from PowerShell.

**Comment by jgiannuzzi** [comment]
Thanks for chiming in, @gitfvb! Would you agree for us to link to your examples in our README?

**Comment by gitfvb** [comment]
Hi @jgiannuzzi , sure. It is an honour for me. Feel free to link me or copy&paste the code you need 😊

**Comment by dburtsev** [comment]
Thank you adamreeve
Can I run _nuget.exe install ParquetSharp_ on my Win10 PC and copy ParquetSharp.dll to the windows server?

>you'd probably be better off writing an application in C#

I am the only one in my team who knows C#. This is why I have to use PowerShell.

**Comment by dburtsev** [comment]
1. I create a directory C:\Lib
2. Run nuget.exe install ParquetSharp.
Installing package 'ParquetSharp' to 'C:\Lib'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='ParquetSharp'&semVerLevel=2.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='ParquetSharp'&semVerLevel=2.0.0 157ms
3. Output od dir command:
Directory of C:\Lib
12/16/2021  09:36 AM    <DIR>          .
12/16/2021  09:36 AM    <DIR>          ..
12/16/2021  09:10 AM    <DIR>          ParquetSharp.4.0.0
12/16/2021  09:10 AM    <DIR>          System.Buffers.4.5.1
12/16/2021  09:10 AM    <DIR>          System.Memory.4.5.4
12/16/2021  09:10 AM    <DIR>          System.Numerics.Vectors.4.5.0
12/16/2021  09:10 AM    <DIR>          System.Runtime.CompilerServices.Unsafe.4.5.3

4. Powershell call 
Add-Type -Path C:\Lib\ParquetSharp.4.0.0\runtimes\win-x64\native\ParquetSharpNative.dll
Add-Type : Could not load file or assembly 'file:///C:\Lib\ParquetSharp.4.0.0\runtimes\win-x64\native\ParquetSharpNative.dll' or one of its dependencies. The module was expected to contain an 
assembly manifest.

**Comment by jgiannuzzi** [comment]
Hi @dburtsev, you are getting this error because you are trying to load the native library directly.
Could you please try the steps that @adamreeve outlined above, or follow the example linked by @gitfvb?

**Comment by dburtsev** [comment]
I copy ParquetSharp.dll, ParquetSharp.xml, and ParquetSharpNative.dll into C:\Lib directory. It works now.
Add-Type -Path C:\Lib\ParquetSharp.dll
Thank you

**Comment by jgiannuzzi** [comment]
As it works for you now @dburtsev, and as @adamreeve has added information to our README in #240, I will now close this issue. Feel free to reopen if needed!
