### ISSUE TITLE
PowerShell ParquetFileWriter: Cannot convert "System.Data.DataColumn" to type "ParquetSharp.Column"

### ISSUE THREAD

**Issue by dburtsev** [G-Research/ParquetSharp#241]
Hello
I would like to save dataTable into parquet file

[Data.DataTable]$dt = New-Object System.Data.DataTable
[Data.DataColumn]$column = New-Object System.Data.DataColumn "Timestamp", ([datetime])
$dt.Columns.Add($column)
[Data.DataColumn]$column = New-Object System.Data.DataColumn "ObjectId", ([int])
$dt.Columns.Add($column)
[Data.DataColumn]$column = New-Object System.Data.DataColumn "Value", ([float])
$file = [ParquetSharp.ParquetFileWriter]::new("test.parquet", $dt.Columns)
$rowGroup = $file.AppendRowGroup()
$file.Close()

Cannot convert argument "columns", with value: "System.Data.DataColumnCollection", for ".ctor" to type "ParquetSharp.Column[]": "Cannot convert value 
"System.Data.DataColumnCollection" to type "ParquetSharp.Column[]". Error: "Cannot convert the "Timestamp" value of type "System.Data.DataColumn" to type "ParquetSharp.Column".""
Thanks

**Comment by adamreeve** [comment]
Hi, the error message is saying that you've provided a value of type `System.Data.DataColumnCollection` to the `ParquetFileWriter` constructor, but it's expecting an array of `ParquetSharp.Column`. If you know up-front the columns needed you can create a `ParquetSharp.Column` array directly, otherwise you'll need to determine this from the DataTable columns.

```powershell
$columns = @(
  (New-Object ParquetSharp.Column ([datetime], "Timestamp")),
  (New-Object ParquetSharp.Column ([int], "ObjectId")),
  (New-Object ParquetSharp.Column ([float], "Value")))
$file = [ParquetSharp.ParquetFileWriter]::new("test.parquet", $columns)
$rowGroup = $file.AppendRowGroup()

[ParquetSharp.LogicalColumnWriter``1[datetime]]$timeCol = $rowGroup.NextColumn().LogicalWriter()
$timeCol.WriteBatch([datetime[]]@((Get-Date), (Get-Date), (Get-Date)))
$timeCol.Dispose()

[ParquetSharp.LogicalColumnWriter``1[int]]$idCol = $rowGroup.NextColumn().LogicalWriter()
$idCol.WriteBatch([int[]]@(1, 2, 3))
$idCol.Dispose()

[ParquetSharp.LogicalColumnWriter``1[float]]$valCol = $rowGroup.NextColumn().LogicalWriter()
$valCol.WriteBatch([float[]]@(1.0, 2.0, 3.0))
$valCol.Dispose()

$rowGroup.Dispose()
$file.Close()
```

**Comment by dburtsev** [comment]
Thanks, @adamreeve 
My task is to get data from the source database into DataTable and save DataTable as a parquet file.
`[Data.DataTable]$dt = New-Object System.Data.DataTable
[Data.DataColumn]$column = New-Object System.Data.DataColumn "Timestamp", ([datetime])
$dt.Columns.Add($column)
[Data.DataColumn]$column = New-Object System.Data.DataColumn "ObjectId", ([int])
$dt.Columns.Add($column)
[Data.DataColumn]$column = New-Object System.Data.DataColumn "Value", ([float])

# Create a ParquetSharp.Column array 
[ParquetSharp.Column[]]$Pcolumns = @()
ForEach($column in $dt.Columns) {
$Pcolumn = New-Object ParquetSharp.Column ($column.DataType, $column.ColumnName)
$Pcolumns += $Pcolumn
}

$file = [ParquetSharp.ParquetFileWriter]::new("test.parquet", $Pcolumns)
$rowGroup = $file.AppendRowGroup()
$file.Close()`

Exception calling ".ctor" with "2" argument(s): "The type initializer for 'ParquetSharp.LogicalTypeFactory' threw an exception."
At C:\Work\Parquet\Untitled-1.ps1:16 char:1
+ $file = [ParquetSharp.ParquetFileWriter]::new("test.parquet", $Pcolum ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeInitializationException

**Comment by adamreeve** [comment]
I can't reproduce that error, your code works for me although I had to add an extra `$dt.Columns.Add($column)` to be able to write 3 columns. Are you able to put the `[ParquetSharp.ParquetFileWriter]::new` line in a `try/catch` block and see what the `InnerException` property is on that `TypeInitializationException`? It looks like evaluation of one of the static members of `LogicalTypeFactory` is throwing an exception but I can't see anything that could obviously be a problem.

**Comment by dburtsev** [comment]
I add missing $dt.Columns.Add($column), reopen VS Code and run the script. No error
How can I point $timeCol.WriteBatch(... to my System.Data.DataColumn ?

**Comment by adamreeve** [comment]
Cool okay. `WriteBatch` expects an array of elements. Because a `DataTable` is row-oriented, you'll probably need to read data from your table row by row and build arrays of data that you can then write to Parquet.

**Comment by dburtsev** [comment]
> read data from your table row by row and build arrays of data

This will be slow in Powershell

**Comment by adamreeve** [comment]
> This will be slow in Powershell

Yes you're right, hopefully there's some way to read batches of columns at once then.

**Comment by dburtsev** [comment]
LINQ for PowerShell
`
[Data.DataTable]$dt = New-Object System.Data.DataTable
[Data.DataColumn]$column = New-Object System.Data.DataColumn "Timestamp", ([System.DateTimeOffset])
$dt.Columns.Add($column)

$colName = 'Timestamp'
$inType = [Data.DataRow]
$outType = [System.DateTimeOffset]
[System.Reflection.TypeInfo]$outType2 = $dt.Columns[$colName].DataType

$outType
$outType2
exit

# add data
[Data.DataRow]$row = $dt.NewRow() # 
$row["Timestamp"] = [DateTimeOffset]::Parse('12/22/2021');
$dt.Rows.Add($row)
$row = $dt.NewRow() # 
$row["Timestamp"] = [DateTimeOffset]::Parse('12/23/2021');
$dt.Rows.Add($row)

# LINQ in C#: int[] results = dt.AsEnumerable().Select(d => d.Field<int>("Id")).ToArray();
# Using reflection, get the open definition of the relevant overload of the 
# static [Linq.Enumerable]::Select() method.
# ("Open" means: its generic type parameters aren't yet bound, i.e. aren't
# yet instantiated with concrete types.)
$selectMethod = [Linq.Enumerable].GetMethods().Where({ 
    $_.Name -eq 'Select' -and $_.GetParameters()[-1].ParameterType.Name -eq 'Func`2'}, 'First')
$colName = 'Timestamp'
  # Close the method with the types at hand and invoke it via reflection.
$results = $selectMethod.MakeGenericMethod([Data.DataRow], [DateTimeOffset]).Invoke(
    # No instance to operate on - the method is static.
    $null,
    # The arguments for the method, as an array.
    (
      [Data.DataRow[]] $dt.Rows, 
      [Func[Data.DataRow,DateTimeOffset]]{ $args[0].$colName }
    )
  )
Write-Host $results
`
