### ISSUE TITLE
Unable to cast object of type 'ParquetSharp.LogicalColumnWriter

### ISSUE THREAD

**Issue by dburtsev** [G-Research/ParquetSharp#248]
VS Code, Windows 10 x64
An unhandled exception of type 'System.InvalidCastException' occurred in ParquetSharp.dll: 'Unable to cast object of type 'ParquetSharp.LogicalColumnWriter`3[System.Int32,System.Int32,System.Int32]' to type 'ParquetSharp.LogicalColumnWriter`1[System.Nullable`1[System.Int32]]'.'
   at System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void* toTypeHnd, Object obj)
   at System.Runtime.CompilerServices.CastHelpers.ChkCastClassSpecial(Void* toTypeHnd, Object obj)
   at System.Runtime.CompilerServices.CastHelpers.ChkCastClass(Void* toTypeHnd, Object obj)
   at ParquetSharp.LogicalColumnWriter.Create[TElementType](ColumnWriter columnWriter, Int32 bufferLength, Type elementTypeOverride)
   at ParquetSharp.ColumnWriter.LogicalWriter[TElement](Int32 bufferLength)
   at testNulls3.Program.Main(String[] args) in C:\Work\Parquet\testNulls3\Program.cs:line 40

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using System.IO;
using ParquetSharp;

namespace testNulls3
{
    class Program
    {
        static void Main(string[] args)
        {
            var numArray = new int?[] { };
            System.Data.DataTable dt = new System.Data.DataTable();
            System.Data.DataColumn column = new System.Data.DataColumn("id", System.Type.GetType("System.Int32"));
            dt.Columns.Add(column);
            DataRow row = dt.NewRow();
            row["id"] = 1;
            dt.Rows.Add(row);
            row = dt.NewRow();
            row["id"] = DBNull.Value;
            dt.Rows.Add(row);

            var columns = new ParquetSharp.Column[dt.Columns.Count];

            for (int i = 0; i < dt.Columns.Count; i++)
            {
                switch (dt.Columns[i].DataType.Name)
                {
                    case "Int32": columns[i] = new ParquetSharp.Column<int>(dt.Columns[i].ColumnName); break;
                }
            }

            using var file = new ParquetFileWriter("C:\\Work\\Parquet\\test.parquet", columns);
            using var rowGroup = file.AppendRowGroup();

            using (var objectIdWriter = rowGroup.NextColumn().LogicalWriter<int?>())
            {
                numArray = dt.AsEnumerable().Select(d => d.Field<int?>(columns[0].Name)).ToArray();
                for (int i = 0; i != numArray.Length; ++i)
                {
                objectIdWriter.WriteBatch(numArray);
                }
            }
            file.Close();
            System.Environment.Exit(0);
        }
    }
}
```

**Comment by adamreeve** [comment]
Hi, the problem is that you create the column with an element type of `int` here:
```c#
columns[i] = new ParquetSharp.Column<int>(dt.Columns[i].ColumnName)
```
but then try to access the writer with an element type of `int?`:
```c#
using (var objectIdWriter = rowGroup.NextColumn().LogicalWriter<int?>())
```
If you change the column type to `int?` then this code works.

The error message is a little confusing as the concrete type of the logical column writer has three type parameters (physical, logical and element types, which are all `System.Int32` from the error message), and accessing the logical writer tries to cast it to the abstract `LogicalColumnWriter` class with a single type parameter for the element type. In this case the element type of `System.Int32` doesn't match the type you're trying to use which is ``System.Nullable`1[System.Int32]`` so you see this exception.

**Comment by dburtsev** [comment]
Works. Thank you @adamreeve 
Note: I have to remove for (int i = 0; i != numArray.Length; ++i) because it creates dublicates.
