### ISSUE TITLE
Support for outputting Parquet from a ReadOnlySpan<T>

### ISSUE THREAD

**Issue by Techrocket9** [G-Research/ParquetSharp#25]
Currently [LogicalColumnWriter](https://github.com/G-Research/ParquetSharp/blob/master/csharp/LogicalColumnWriter.cs) requires you to [pass an array into WriteBatch](https://github.com/G-Research/ParquetSharp/blob/545590099a369e5d077672ec373be875bca4a584/csharp/LogicalColumnWriter.cs#L96).

This is fine for use cases where the quantity of data to be written is known at the start of data collection since you can buffer your columns in arrays, but for use cases where the quantity is unknown you have to use an expandable type that will inevitably have some unused array space left over at the end when it comes time to write out the resultant Parquet file.

In most cases you'd work around this by copying your data into an exact-fit array before passing it to the Parquet library (.toArray). However, this is resource-prohibitive in memory-constrained environments when working with large data sets.

Internally, ParquetSharp uses [Span](https://msdn.microsoft.com/en-us/magazine/mt814808.aspx) types to avoid unnecessary copies. There's even a (private) [method](https://github.com/G-Research/ParquetSharp/blob/545590099a369e5d077672ec373be875bca4a584/csharp/LogicalColumnWriter.cs#L204) to take a ReadOnlySpan and sink it to Parquet format.

It would be very helpful if a variant of the WriteBatch API were exposed that accepted a ReadOnlySpan\<T\> directly to avoid this extra memory copy. For my current use case array support would be unnecessary, but in general it would be nice to have.

**Comment by GPSnoopy** [comment]
Hi,

Well spotted! 

The library is indeed inconsistent with its use of Span<>. The rule was not to use it in public APIs as the library had to interface with older .NET applications.

The two existing methods are:
WriteBatch(TElement[] values)
WriteBatch(TElement[] values, int start, int length)

Proposal is to add:
WriteBatch(ReadOnlySpan<TElement> values)
and implement the other two methods on top of this one.

Ideally it should probably be the only method for writing, but I'm not sure we're ready yet to move to an all-Span world.

**Comment by GPSnoopy** [comment]
This should be fixed in 1.4.0.2-beta3.
