### ISSUE TITLE
MS SQL -> DataTable -> Parquet -> Redshift (not issue)

### ISSUE THREAD

**Issue by dburtsev** [G-Research/ParquetSharp#253]
Hello all
This is the beta version of my ETL. I am using VS Code/Windows 10/.NET 6.0.
The task - get MS SQL table name in runtime, recreate this table in Amazon redshift, and copy data using Parquet file.
Additional task: Redshift doesn't support VARCHAR(MAX). Maximum is 65535 - convert varchar(max) to varchar(65535).
Convert all diacritic/accent characters to US Engish (ō -> o)
[https://github.com/dburtsev/CSharp/blob/main/Program.cs](url)
Thanks,
Dmitriy

**Comment by jgiannuzzi** [comment]
Hi @dburtsev,

Thanks _a lot_ for your interest in ParquetSharp — we all really appreciate how you're pushing the library in new directions!

May I however please ask you not to open an issue to share your ETL code? We would like to keep issues as a way to track questions, bug reports, and feature requests.

I believe the code you are sharing has value for the community but would be better as a comment in one of your previous issues, or even better, as a new [discussion](https://github.com/G-Research/ParquetSharp/discussions).

Thanks for your understanding!
