### ISSUE TITLE
Configurable timestamp format for Parquet Writer

### ISSUE THREAD

**Issue by matthros** [G-Research/ParquetSharp#256]
All of my C# Datetime objects are translated into Timestamp in microseconds. I want them in ms.
The timestamp format should be configurable like in pyarrow to_parquet method where you are able to specify the coerce timestamps parameter.

Maybe I am wrong and it is already possible in v5.0.0 @GPSnoopy ?

**Comment by adamreeve** [comment]
Hi @matthros, this is possible by passing the `logicalTypeOverride` parameter to the `Column` constructor when configuring your writer. For example:

```C#
var columns = new Column[]
{
    new Column<DateTime>("Timestamp", LogicalType.Timestamp(true, TimeUnit.Millis)),
    new Column<int>("ObjectId"),
    new Column<float>("Value")
};

using var fileWriter = new ParquetFileWriter("test.parquet", columns);
```

**Comment by matthros** [comment]
@adamreeve Thx, perfect. I think the documentation could be expanded ;-)

**Comment by adamreeve** [comment]
Yes I agree, I've had a go at improving the documentation in #257.
