### ISSUE TITLE
Any plans to support streams as a parquet source?

### ISSUE THREAD

**Issue by markpattison** [G-Research/ParquetSharp#259]
For example, this would enable ParquetSharp to access files stored in the cloud without downloading the entire file first.

My particular use case is for files in Azure Data Lake.

**Comment by adamreeve** [comment]
Hi Mark. The Parquet format isn't really designed to support this use case. It has a footer at the end with the schema and metadata that must be read before you can read any row-group data. This allows writing the file in one pass, but means for reading you need to be able to seek to the end of the file first. We do support reading data from a dotnet stream but it must be a seekable stream for this reason. Eg:
```csharp
using var input = new ParquetSharp.IO.ManagedRandomAccessFile(File.OpenRead("data.parquet"));
using var fileReader = new ParquetSharp.ParquetFileReader(input);
```

**Comment by markpattison** [comment]
Thanks for the prompt suggestion.  I have a [seekable](ManagedRandomAccessFile) stream from the data lake, so that's not an issue.

I've tried using `ManagedRandomAccessFile` as in your snippet and it reads the file perfectly well.

I'm now getting a CLR error sometime after finishing reading the file... I'll raise a separate issue if I can't get to the bottom of it.
