### ISSUE TITLE
ParquetSharp should take into account "isAdjustedToUTC" for Timestamps

### ISSUE THREAD

**Issue by adeboyed** [G-Research/ParquetSharp#260]
Quality of life improvement.

ParquetSharp by default returns DateTimes with [`DateTime.Kind`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.kind?view=net-6.0) equal to `Unspecified`.
ParquetSharp can be a bit smarter and use `isAdjustedToUTC` field from the Parquet Format to specify the `DateTime.Kind` as `DateTime.Utc`

By default, ParquetSharp uses `new DateTime()` which returns an `DateTime.Kind.Unspecified` variant.

**Comment by adamreeve** [comment]
Yes I think this would make sense. This would be a breaking change though, and would change the behaviour for existing code as well as require a change in the public API. I've made a draft PR at #261 that implements this.

ParquetSharp defaults to writing `DateTime` values with `isAdjustedToUtc: true` (https://github.com/G-Research/ParquetSharp/blob/b9f2f71b01d4eaebc63c2a972b43a07efa575dc2/csharp/LogicalTypeFactory.cs#L199). So after this change, if you write `DateTime` values with `Kind = DateTimeKind.Unspecified` and don't override the logical type, you'll get back `DateTime` values with `Kind = DateTimeKind.Utc`. You would need to specify a logical type override when writing data to ensure `isAdjustedToUtc` is set correctly.

This is still an improvement over current behaviour though where you always get back `DateTimeKind.Unspecified` values unless you implement a custom `LogicalReadConverterFactory`.

**Comment by Nisden** [comment]
Can we have an option to disable this behavior?
For consistency we can't use isAdjustedToUtc, as Azure Synapse Serverless refuse to read Timestamp values that have it set.

**Comment by adamreeve** [comment]
Hi Nick, yes okay if we do make this change I'll make sure it's configurable. But if this is going to cause compatibility issues then maybe it's best to just leave things as is, or make the new behaviour opt-in.

**Comment by Nisden** [comment]
@adamreeve Thinking about it, the behavior will only change when you set isAdjustedToUTC=true, so it wont really change anything for us, as we can't use isAdjustedToUTC anyways. 

It should still be noted that quite a few systems ignore or breaks with isAdjustedToUTC. Azure Synapse Serverless breaks, and I know the Apache Drill ignores it.

**Comment by adamreeve** [comment]
Yes the proposed change only affects reading Parquet data into dotnet DateTime values. When writing DateTimes, we currently default to using `isAdjustedToUtc: true`, and there isn't really a way to infer what this should be so we're not suggesting changing how data is written.

So from what you're saying, it sounds like you already need to specify `isAdjustedToUtc: false` when writing files for compatibility with Azure Synapse Serverless. And there probably isn't a need to make the default reading behaviour configurable then.

**Comment by Nisden** [comment]
HI @adamreeve 

Just a small follow up.... So I have been feeding you the wrong information before. 

Azure Synapse Serverless only supports `isAdjustedToUTC=true`
And we do actually save "locally adjusted" DateTime's to Parquet, so getting `DateTimeKind.UTC `is kinda of a pain.

For now I have implemented a workaround
```
public class CustomLogicalReadConverterFactory : LogicalReadConverterFactory
    {
        private readonly bool forceDateTimeKindUnspecified;

        public CustomLogicalReadConverterFactory(bool forceDateTimeKindUnspecified)
        {
            this.forceDateTimeKindUnspecified = forceDateTimeKindUnspecified;
        }

        public override Delegate GetConverter<TLogical, TPhysical>(ColumnDescriptor columnDescriptor, ColumnChunkMetaData columnChunkMetaData)
        {
            if (forceDateTimeKindUnspecified && typeof(TLogical) == typeof(DateTime))
            {
                var timestampType = (TimestampLogicalType)columnDescriptor.LogicalType;
                switch (timestampType.TimeUnit)
                {
                    case TimeUnit.Millis:
                        return (LogicalRead<DateTime, long>.Converter)((s, _, d, _) => LogicalRead.ConvertDateTimeMillis(s, d, DateTimeKind.Unspecified));
                    case TimeUnit.Micros:
                        return (LogicalRead<DateTime, long>.Converter)((s, _, d, _) => LogicalRead.ConvertDateTimeMicros(s, d, DateTimeKind.Unspecified));
                }
            }

            if (forceDateTimeKindUnspecified && typeof(TLogical) == typeof(DateTime?))
            {
                var timestampType = (TimestampLogicalType)columnDescriptor.LogicalType  ;
                switch (timestampType.TimeUnit)
                {
                    case TimeUnit.Millis:
                        return (LogicalRead<DateTime?, long>.Converter)(
                            (source, rep, dest, def) => LogicalRead.ConvertDateTimeMillis(source, rep, dest, def, DateTimeKind.Unspecified));
                    case TimeUnit.Micros:
                        return (LogicalRead<DateTime?, long>.Converter)(
                            (source, rep, dest, def) => LogicalRead.ConvertDateTimeMicros(source, rep, dest, def, DateTimeKind.Unspecified));
                    case TimeUnit.Nanos:
                        return (LogicalRead<TPhysical?, TPhysical>.Converter)LogicalRead.ConvertNative;
                }
            }

            return base.GetConverter<TLogical, TPhysical>(columnDescriptor, columnChunkMetaData);
        }
    }
```

And ill try and open up a ticket with Microsoft for an actual solution that will allow use to use `isAdjustedToUtc=false`
