### ISSUE TITLE
Exception on partial read of stream: tried reading x bytes starting at position y from file but only got z

### ISSUE THREAD

**Issue by delreluca** [G-Research/ParquetSharp#263]
I am trying to read a parquet file from the cloud (Azure Data Lake). The stream is seekable, so I do it like suggested in #259 

I get a `ParquetException` though. It seems like sometimes only partial reads are performed. I tried the same operation in Parquet.NET and it worked.

Here is the exception:

```
Message
class parquet::ParquetException (message: ’Tried reading 11036647 bytes starting at position 2848913 from file but only got 4194304’)

Stack Trace
at ParquetSharp.ExceptionInfo.Check(IntPtr exceptionInfo)
at ParquetSharp.ExceptionInfo.Return[TArg0,TValue](IntPtr handle, TArg0 arg0, GetFuction`2 getter)
at ParquetSharp.ExceptionInfo.Return[TArg0,TValue](ParquetHandle handle, TArg0 arg0, GetFunction`2 getter)
at ParquetSharp.RowGroupReader.Column(Int32 i)
```

The part where you perform the read seems to forward the number of bytes read correctly: https://github.com/G-Research/ParquetSharp/blob/ca3d372febfb3ec3b1b3b737096164c446183e0d/csharp/IO/ManagedRandomAccessFile.cs#L47-L58

I guess the underlying C++ library does not support partial reads. It could be handled by `ManagedRandomAccessFile` by repeating reads until the buffer is full.

**Comment by adamreeve** [comment]
Hi @delreluca, thanks for the bug report. Yes I think it would make sense to handle this within `ManagedRandomAccessFile`, from the comment here it looks like the underlying Arrow interface expects that `nbytes` are read unless the end of the file is reached, although it's not very clear: https://github.com/apache/arrow/blob/a589a3d985801ba86e36e66ff3c652698511a311/cpp/src/arrow/io/interfaces.h#L191-L194

**Comment by delreluca** [comment]
I haven’t had time to look into this myself until now and am struggling with the build setup (vcpkg fails at snappy, although it seems I can just extract the binary from the v6 nupkg for just doing C# development) just to realise you already had a go at it 😄 So I just wanted to say many thanks for the quick response!
