### ISSUE TITLE
Exception while reading a column value - ParquetSharp.ParquetException: class parquet::ParquetStatusException (message: 'IOError: Corrupt snappy compressed data.')

### ISSUE THREAD

**Issue by manums** [G-Research/ParquetSharp#269]
Compression used - snappy
Row groups - 1

Issue - `ColumnReader.ReadBatch` is throwing exception with Corrupt data. pyspark can read the data from the same parquet file without any issues. 

Please share any suggestions for to workaround or to fix this issue. 

Schema - 5 string fields and a timestamp field. 

Exception details:

ParquetSharp.ParquetException: class parquet::ParquetStatusException (message: 'IOError: Corrupt snappy compressed data.')
   at ParquetSharp.ExceptionInfo.Check(IntPtr exceptionInfo)
   at ParquetSharp.ExceptionInfo.Return[TValue](IntPtr handle, GetFunction`1 getter)
   at ParquetSharp.ExceptionInfo.Return[TValue](ParquetHandle handle, GetFunction`1 getter)
   at <<CUSTOM>>.Data.Parquet.ColumnEnumerator`1.<GetColumnElements>d__6.MoveNext()

Here MoveNext is just calling into trying to get next value from the column using parquet column buffer. 

![image](https://user-images.githubusercontent.com/3592179/164566291-f0836843-6fb5-4fb6-88d8-9169edc673b3.png)

**Comment by adamreeve** [comment]
Hi @manums, thanks for the bug report. If I generate a similar file using snappy compression I'm able to read it without any issue. Are you able to provide more details on how this file has been created or provide an example file that reproduces this error?

If this file was written by Spark it looks as if this could be the same as this issue reported upstream at https://issues.apache.org/jira/browse/ARROW-6057. That looks like a bug in Spark to me if it's writing the Parquet version number as 1 in the footer but implementing version 2.

**Comment by EnricoMi** [comment]
I was able to reproduce the issue in ARROW_6057. Maybe such a file reproduces this issue here as well:

```
./spark-3.5.5-bin-hadoop3/bin/spark-shell --conf spark.hadoop.parquet.writer.version="v2"
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.5.5
      /_/
         
Using Scala version 2.12.18 (OpenJDK 64-Bit Server VM, Java 11.0.26)
Type in expressions to have them evaluated.
Type :help for more information.

scala> Seq(Option.empty[Float]).toDS.write.parquet("parquet-v2-example.parquet")
```

**Comment by EnricoMi** [comment]
Issue ARROW-6057 was a reader-side issue, Spark / Java Parquet writes a correct v2 file.
