### ISSUE TITLE
Alpine 3.15 - Unable to load shared library 'ParquetSharpNative' or one of its dependencies.

### ISSUE THREAD

**Issue by dalumedic** [G-Research/ParquetSharp#278]
I am experiencing "the" missing-native-lib-issue when running in a Alpine 3.15 container (6.0-alpine).  I switched to Ubuntu 22.04 (6.0-jammy) and it worked fine.  Re: https://hub.docker.com/_/microsoft-dotnet-sdk

Similar issue: https://github.com/G-Research/ParquetSharp/issues/273

**Comment by adamreeve** [comment]
Hi @dalumedic, thanks for the bug report. Which version of ParquetSharp are you using, are you still seeing this with ParquetSharp 7.0.0?

I would guess this is because Alpine uses musl rather than glibc. Installing gcompat might help (see https://wiki.alpinelinux.org/wiki/Running_glibc_programs).

**Comment by adamreeve** [comment]
I'm closing this as answered as we don't currently have any plans to support musl.
