### ISSUE TITLE
Support reading string columns with repetition set to required

### ISSUE THREAD

**Issue by vikramrkin** [G-Research/ParquetSharp#292]
Hi G-Research Team/Contributors,

I am using ParquetSharp library from last 6-8 months and recently noticed an issue when reading a .parquet file which I had received from a client. I am using version 7.0.0, .Net Framework 4.8.

I have created a sample project to replicate the error which can be found here:

https://github.com/vikramrkin/PArquetSharpBugTest

Most columns are read back fine except one which gives the exception:
```
Exception: System.ArgumentOutOfRangeException: unsupported logical type String with physical type ByteArray
Parameter name: logicalType
   at ParquetSharp.LogicalTypeFactory.GetSystemTypes(ColumnDescriptor descriptor)
   at ParquetSharp.LogicalTypeFactory.GetSystemTypes(ColumnDescriptor descriptor, Type columnLogicalTypeOverride)
   at ParquetSharp.ColumnDescriptor.GetSystemTypes(LogicalTypeFactory typeFactory, Type columnLogicalTypeOverride)
   at ParquetSharp.ColumnDescriptor.Apply[TReturn](LogicalTypeFactory typeFactory, Type columnLogicalTypeOverride, IColumnDescriptorVisitor`1 visitor)
   at ParquetSharp.LogicalColumnReader.Create(ColumnReader columnReader, Int32 bufferLength, Type elementTypeOverride)
   at ParquetSharp.LogicalColumnReader.Create[TElement](ColumnReader columnReader, Int32 bufferLength, Type elementTypeOverride)
   at ParquetSharpBugTest.Program.Main(String[] args) in D:\src\ParquetSharpBugTest\ParquetSharpBugTest\Program.cs:line 43

```

The parquet file in question (part of the repo mentioned above) can be opened successfully in ParquetViewer and metadata looks fine.

Appreciate any help.

Thanks
Vik

**Comment by vikramrkin** [comment]
After debugging ParquetSharp code using the file attached in above codebase, the field in question has its "Repetition type" set to "Required". As a result, LogicalTypeFactory.GetSystemTypes() is unable to find a primitive mapping and throws the exception.


Can someone please explain the significance of this?

**Comment by adamreeve** [comment]
Hi @vikramrkin, thanks for the bug report and providing a way to reproduce the issue! The problem is that in C# a string is a reference type so may be null, so we always write strings with repetition set to optional. But there isn't a good reason why we shouldn't be able to read required string values. We're currently constrained by only mapping a dotnet type to a single `(LogicalType, Repetition, PhysicalType)` tuple, but it seems like we should allow multiple possible mappings when reading a column.

You can work around this in the meantime with a custom `LogicalTypeFactory`. Unfortunately there's an issue with the `LogicalRead.ConvertString` method where it doesn't handle definition levels not being present (as they're always present for optional columns) so you also need to implement a custom `LogicalReadConverterFactory`:
```C#
class CustomLogicalTypeFactory : LogicalTypeFactory
{
    public override (Type physicalType, Type logicalType) GetSystemTypes(ColumnDescriptor descriptor)
    {
        var physicalType = descriptor.PhysicalType;
        using var logicalType = descriptor.LogicalType;
        using var schemaNode = descriptor.SchemaNode;
        var repetition = schemaNode.Repetition;

        if (logicalType is StringLogicalType &&
            physicalType == PhysicalType.ByteArray &&
            repetition == Repetition.Required)
        {
            return (typeof(ByteArray), typeof(string));
        }

        return base.GetSystemTypes(descriptor);
    }
}

class CustomLogicalReadConverterFactory : LogicalReadConverterFactory
{
    public override Delegate GetConverter<TLogical, TPhysical>(ColumnDescriptor columnDescriptor, ColumnChunkMetaData columnChunkMetaData)
    {
        if (typeof(TLogical) == typeof(string))
        {
            var byteArrayCache = new ByteArrayReaderCache<TPhysical, TLogical>(columnChunkMetaData);

            return byteArrayCache.IsUsable
                ? (LogicalRead<string?, ByteArray>.Converter) ((s, dl, d, del) => ConvertString(s, dl, d, del, (ByteArrayReaderCache<ByteArray, string>) (object) byteArrayCache))
                : LogicalRead.ConvertString;
        }
        return base.GetConverter<TLogical, TPhysical>(columnDescriptor, columnChunkMetaData);
    }
    
    public static void ConvertString(ReadOnlySpan<ByteArray> source, ReadOnlySpan<short> defLevels, Span<string?> destination, short definedLevel, ByteArrayReaderCache<ByteArray, string> byteArrayCache)
    {
        for (int i = 0, src = 0; i < destination.Length; ++i)
        {
            destination[i] = defLevels.IsEmpty || defLevels[i] == definedLevel ? LogicalRead.ToString(source[src++], byteArrayCache) : null;
        }
    }
}
```

You can then use these with:
```C#
using var parquetReader = new ParquetFileReader(filePath)
{
    LogicalTypeFactory = new CustomLogicalTypeFactory(),
    LogicalReadConverterFactory = new CustomLogicalReadConverterFactory(),
};
```

**Comment by vikramrkin** [comment]
Thanks @adamreeve . Will try out this suggestion.
