### ISSUE TITLE
Strong name for the assemblies in the nuget packages

### ISSUE THREAD

**Issue by DanSmith** [G-Research/ParquetSharp#296]
Do you have an opinion on adding a strong name to the ParquetSharp assembly? There are some instances on the .NET Framework on Windows where this can make integration much easier. Doing a manual strong naming combined with managing the native assemblies in MS build adds a bit of complexity vs having this built in into the nuget package.

Microsoft has updated its guidance and now says projects should consider strong naming your open-source .NET libraries, and check the key into the public source control as well.
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

I would be happy to do this and submit a PR if you are open to it. Thanks.

**Comment by adamreeve** [comment]
Hi Dan, apologies for the slow reply, but yes we'd be happy for you to submit a PR for this. It seems like the downsides are fairly minor and having a strong named assembly could be quite useful for some users.

**Comment by adamreeve** [comment]
Closing as won't fix, see the discussion in #298
