### ISSUE TITLE
ManagedRandomAccessFile: A callback was made on a garbage collected delegate

### ISSUE THREAD

**Issue by delreluca** [G-Research/ParquetSharp#312]
on: netcoreapp3.1, ASP.NET Core, Kestrel, Windows 10 x64, ParquetSharp 8.0.0 (also with 6.0.1)

Consider the following snippet

```csharp
// a 300 MB Parquet, does not really matter, happens with other streams as well
using (var stream = File.OpenRead(path))
using (var reader = new ParquetFileReader(new ManagedRandomAccessFile(stream, true)))
{
  // nop
}

// it also happens when I allocate some arrays for data reading
GC.Collect(3, GCCollectionMode.Forced, blocking:true);
```

When I execute this twice in my web app the server process gets terminated. On the console I see:
```
Process terminated. A callback was made on a garbage collected delegate of type 'ParquetSharp!ParquetSharp.IO.ManagedRandomAccessFile+CloseDelegate::Invoke'.
   at ParquetSharp.IO.RandomAccessFile.RandomAccessFile_Free(IntPtr)
   at ParquetSharp.IO.RandomAccessFile.RandomAccessFile_Free(IntPtr)
   at ParquetSharp.ParquetHandle.Finalize()

Process finished with exit code -2,146,232,797.
```

My guess is that the `ManagedRandomAccessFile` goes out of scope but a native pointer to one of its delegates is still in use? The `ParquetHandle` does not seem to capture the instance itself.

I hope it’s not too hard to reproduce. Working around by keeping the reference is possible it seems:

```csharp
using (var stream = File.OpenRead(path))
using (var m = new ManagedRandomAccessFile(stream, true))
using (var reader = new ParquetFileReader(m))
{
  // nop
}

GC.Collect(3, GCCollectionMode.Forced, blocking:true);

// This seems to work.
```

**Comment by adamreeve** [comment]
Hi @delreluca, yes your explanation for what is happening is correct. `ManagedRandomAccessFile` is `IDisposable` so it's intended to be used with a `using` statement and only disposed after it is no longer needed.

This isn't the first time someone has run into this issue though, see #266 for example. So it would probably make sense for `ParquetFileReader` to keep a handle to the  `RandomAccessFile` to avoid this issue. And similarly, `ParquetFileWriter` should keep a handle to an `OutputStream` when one is used.

**Comment by delreluca** [comment]
Ah, I missed that issue, sorry. Thanks for confirming my explanation, I can just fix my code with the additional `using` then.

I would welcome remembering the handle since I would have expected an `IDisposable` to also dispose of whatever it received as a reference in its constructor. (Not sure if that is a written best practice? Just a gut feeling)

**Comment by adamreeve** [comment]
This has been fixed on master now, you should still dispose of the `ManagedRandomAccessFile` yourself with a `using` statement, but ParquetSharp should no longer crash if you don't.
