### ISSUE TITLE
Exception when loading decimal (10,4) column

### ISSUE THREAD

**Issue by fan130** [G-Research/ParquetSharp#314]
Hi,
I have a parquet file which was generated from a SQL Server table which has a smallmoney column, and this column has been serialized as a decimal (10, 4) column whose physical type is INT64. When I tried to use ParquetSharp to load the file and get the logical reader like: rowGroupReader.Column(2).LogicalReader<decimal>(); I got following exception:

System.NotSupportedException
  HResult=0x80131515
  Message=only 16 bytes of decimal length is supported
  Source=ParquetSharp
  StackTrace:
   at ParquetSharp.LogicalTypeFactory.GetSystemTypes(ColumnDescriptor descriptor)
   at ParquetSharp.LogicalTypeFactory.GetSystemTypes(ColumnDescriptor descriptor, Type columnLogicalTypeOverride)
   at ParquetSharp.ColumnDescriptor.GetSystemTypes(LogicalTypeFactory typeFactory, Type columnLogicalTypeOverride)
   at ParquetSharp.ColumnDescriptor.Apply[TReturn](LogicalTypeFactory typeFactory, Type columnLogicalTypeOverride, IColumnDescriptorVisitor`1 visitor)
   at ParquetSharp.LogicalColumnReader.Create(ColumnReader columnReader, Int32 bufferLength, Type elementTypeOverride)
   at ParquetSharp.LogicalColumnReader.Create[TElement](ColumnReader columnReader, Int32 bufferLength, Type elementTypeOverride)
   at Program.<Main>$(String[] args) 

So does that mean ParquetSharp doesn't support decimal columns whose physical type is INT64? Thanks

**Comment by adamreeve** [comment]
Hi, yes we currently only support reading decimal values stored as fixed length byte arrays with 16 bytes. There's a related issue open for supporting writing data with different precision (#252).

**Comment by fan130** [comment]
Thanks for the information! Currently I have to work around by modifying the code of ParquetSharp so as to support reading decimal columns whose physical type is INT64. I'd like to know if you have any ETA to officially support this?

**Comment by adamreeve** [comment]
No we don't currently have this scheduled to be worked on so don't have an ETA, but we would like to implement this eventually. We'd also be open to accepting a PR to implement this feature. Would you be willing to work on this, or can you share the code changes you've made to handle int64 reading already? Ideally we'd like to support arbitrary length `fixed_len_byte_array` values eventually but handling int64 values would be useful by itself.

**Comment by fan130** [comment]
My implementation just supports reading decimal column whose physical type is INT64, which is enough to unblock my current work, but seems not a complete feature. Actually I'm a just new user of parquet format and ParquetSharp, so I do have no confidence on my current implementation. Of course it's my honor if my implementation can help you on this feature, feel free to check it out at: https://github.com/fan130/ParquetSharp/commit/7b7a5d4968a6ac35cde96d4b2343cfd5a5b26f36

**Comment by adamreeve** [comment]
Awesome, thanks @fan130, I've opened #315 based on your changes and also added support for int32 data. Supporting arbitrary length fixed-length byte array data is still to be done though.

**Comment by fan130** [comment]
Good to know. Thanks a lot for your quick action!
