### ISSUE TITLE
Access PageIndex

### ISSUE THREAD

**Issue by nazar554** [G-Research/ParquetSharp#325]
I see there are methods to get row group statistics, is there a way to read/write parquet page indexes?

**Comment by adamreeve** [comment]
Hi, no there isn't a way to do this with ParquetSharp currently, and I believe this isn't supported by the underlying Arrow C++ library we use. It looks like implementing read support is in progress though: https://issues.apache.org/jira/browse/ARROW-10158

**Comment by adamreeve** [comment]
Closing this as not planned for now, if this is implemented in Arrow Parquet we could revisit this.
