### ISSUE TITLE
[Read] Read Decimal LogicalType

### ISSUE THREAD

**Issue by Platob** [G-Research/ParquetSharp#328]
Hello,

Do you have any example to read a decimal column in a parquet file ?

I am stuck on error "System.NotSupportedException: only 16 bytes of decimal length is supported"

PhysicalType = FixedLenByteArray

i dont find workaround since it breaks whenever i call Column.LogicalReader<T>

Maybe is there a method to get raw data like Column.PhysicalReader<T> ?

Br
Nick

What i tried so far:

```
case LogicalTypeEnum.Decimal:
      return column.LogicalReader<decimal?>().ReadAll(numRows)
          .Select(l => (object)l)
          .ToArray();
```

**Comment by adamreeve** [comment]
Hi @Platob, which version of ParquetSharp are you using, and do you know the byte width of the decimal data you are trying to read? If your data uses a physical type of int32 or int64 then support for reading this has been added in ParquetSharp 10.0.1-beta1 (#315).

Otherwise we only currently support reading fixed-length byte array based decimal data that uses 16 bytes, but it is possible to read the raw byte values. See https://github.com/G-Research/ParquetSharp/discussions/317#discussioncomment-4210430 for an example that just prints a hex representation of the byte values.

**Comment by Platob** [comment]
I use the 8.0.0 version, sadly i dont have hand the physical type parquet file generation

I was casting in float / double, but i would like be faster
But i can cast it in several (Precision, Scale), i the max i could write = decimal128(29,22) but it does not fit in 16b

I will go with https://github.com/G-Research/ParquetSharp/discussions/317#discussioncomment-4210430

thanks a lot

**Comment by Platob** [comment]
After some brain thinking i did this, but it needs non nullable instances,

@adamreeve  Do you know how to create a nullable column reader ?

```csharp
case LogicalTypeEnum.Decimal:
                    var typeLength = column.ColumnDescriptor.TypeLength;
                    var values = new FixedLenByteArray?[numRows];
                    var _column = (ColumnReader<FixedLenByteArray?>)column;
                    var rowsRead = _column.ReadBatch(numRows, values, out var valuesRead);
                    var bytes = new byte[typeLength];

                    return Enumerable.Range(0, numRows)
                        .Select(i =>
                        {
                            Marshal.Copy(values[i].Pointer, bytes, 0, typeLength);

                            // Parse the string as a decimal value
                            Console.WriteLine(ConvertFixedLengthByteArrayToDecimal(bytes, column.ColumnDescriptor.TypePrecision, column.ColumnDescriptor.TypeScale));
                            return (object)ConvertFixedLengthByteArrayToDecimal(bytes, column.ColumnDescriptor.TypePrecision, column.ColumnDescriptor.TypeScale);
                        })
                        .ToArray();
````

Static Method

```csharp
static decimal ConvertFixedLengthByteArrayToDecimal(byte[] bytes, int scale)
        {
            // Convert the byte array to a decimal value
            decimal value = decimal.Zero;

            for (int i = 0; i < bytes.Length; i++)
            {
                value += bytes[i] * (decimal)Math.Pow(256, i);
            }

            // Adjust the value to the correct scale
            value /= (decimal)Math.Pow(10, scale);

            return value;
        }
```

**Comment by adamreeve** [comment]
To handle nullable values you need to use the `ReadBatch` override that takes `defLevels` and `repLevels`. In the case of a column of scalar nullable values (not nested in an array or other struct) then `repLevels` can be ignored. Eg. something like this should work:
```c#
var typeLength = column.ColumnDescriptor.TypeLength;
var definitionLevel = column.ColumnDescriptor.MaxDefinitionLevel;
var values = new FixedLenByteArray[numRows];
var defLevels = new short[numRows];
var bytes = new byte[typeLength];

var decimalValues = new List<decimal?>();

// create byte vector values
var coefs = Enumerable.Range(0, column.ColumnDescriptor.TypeLength)
    .Reverse()
    .Select(iB => (decimal)Math.Pow(256, iB))
    .ToArray();

long totalRowsRead = 0;
while (totalRowsRead < numRows)
{
    var rowsRead = _column.ReadBatch(numRows, defLevels, null, values, out var valuesRead);
    var valueIdx = 0;
    for (var i = 0; i < rowsRead; ++i)
    {
        if (defLevels[i] == definitionLevel)
        {
            Marshal.Copy(values[valueIdx].Pointer, bytes, 0, typeLength);
            // Parse the string as a decimal value
            decimalValues.Add(ConvertFixedLengthByteArrayToDecimal(bytes, column.ColumnDescriptor.TypeScale, coefs));
            valueIdx++;
        }
        else
        {
            decimalValues.Add(null);
        }
    }

    totalRowsRead += rowsRead;
}
```

**Comment by Platob** [comment]
Damn you rock ! thanks a lot
