### ISSUE TITLE
Clarify nesting example "objects" status

### ISSUE THREAD

**Issue by jmandel** [G-Research/ParquetSharp#339]
In following example from the nesting documentation at https://github.com/G-Research/ParquetSharp/blob/f5148e3c681e8c24fedc8dca5f742d9ae2456cea/docs/Nested.md?plain=1#L53 ...

```
// Create a group node containing the two nested fields
using var groupNode = new GroupNode(
        "objects", Repetition.Optional, new Node[] {messageNode, idsNode});
```

Shows an optional group node called objects. But in the JSON above, objects is an array. It would be great if the documentation could clarify why "Repeated" is not needed here, when it is used for the array of `id` inside the object.

**Comment by adamreeve** [comment]
Hi @jmandel, good point, I'll update the documentation to make this a bit clearer. But briefly, the reason objects isn't repeated is that this example is showing how to store a single array of objects in the Parquet file, so each logical row contains one object.

If you wanted to store something like the full JSON document in that example per row then you would indeed need to have repeated objects using the same three-level list schema used for `ids`.
