### ISSUE TITLE
Allow logical type override for decimal when logical system type (c# type) is not decimal

### ISSUE THREAD

**Issue by parquetsharp** [G-Research/ParquetSharp#347]
Currently when we create ParquetSharp column for decimal type, it only allows decimal logical type override for Decimal128. However, we are extending the type factory and converter factory to support other precision of decimal and due to this check, we cannot define column with our own implemented BigDecimal based on decimal logical type override. Instead, we have to create the schema node which is kind of hack as currently the offical extension support is to extend type factory and converter factory. Suggest to add one more check in the condition as below which only checks for c# decimal:
```
if (logicalTypeOverride is DecimalLogicalType decimalLogicalType && (logicalSystemType == typeof(decimal) || logicalSystemType == typeof(decimal?))
{
    // For the moment we only support serializing decimal to Decimal128.
    // This reflects the C# decimal structure with 28-29 digits precision.
    // Will implement 32-bits, 64-bits and other precision later.
    if (decimalLogicalType.Precision != 29)
    {
        throw new NotSupportedException("only 29 digits of precision is currently supported for decimal type");
    }

    if (length != sizeof(Decimal128))
    {
        throw new NotSupportedException("only 16 bytes of length is currently supported for decimal type ");
    }
}
```

**Comment by adamreeve** [comment]
Hi, thanks for raising this issue. I think it probably makes sense to move this check into the default `LogicalWriteConverterFactory` as then users could also have a custom converter for the system `decimal` type. I'll make a PR for this shortly.

**Comment by parquetsharp** [comment]
Thanks @adamreeve for help. It's impressive efficiency.
