### ISSUE TITLE
Is SIMD automatically supported in ParquetSharp

### ISSUE THREAD

**Issue by parquetsharp** [G-Research/ParquetSharp#350]
Hi experts, as I checked Apache arrow, https://arrow.apache.org/docs/cpp/env_vars.html#envvar-ARROW_USER_SIMD_LEVEL is supported at runtime. Is this also true for ParquetSharp?

**Comment by adamreeve** [comment]
Hi, yes we don't do any special configuration of the Arrow build to change SIMD settings so this should apply to ParquetSharp. That said, I'm not sure there is much use of runtime SIMD detection in the Parquet implementation, from a quick grep in the code I only found this used in some level comparison code here: https://github.com/apache/arrow/blob/apache-arrow-10.0.1/cpp/src/parquet/level_comparison.cc

**Comment by adamreeve** [comment]
Closing this as answered, but feel free to ask if you have any further questions.
