### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'ParquetSharpNative' 

### ISSUE THREAD

**Issue by milhousemanastorm** [G-Research/ParquetSharp#351]
My Web application is using ParquetSharp to parse parquet file and is working fine on my local. When I deployed it to Azure Web App, I got this error message:

"System.TypeInitializationException: The type initializer for 'ParquetSharp.LogicalTypeFactory' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'ParquetSharpNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at ParquetSharp.LogicalType.LogicalType_None(IntPtr& logicalType)
   at ParquetSharp.ExceptionInfo.Return[TValue](GetAction`1 getter)
   at ParquetSharp.LogicalType.None()
   at ParquetSharp.LogicalTypeFactory..cctor()
   --- End of inner exception stack trace ---
   at ParquetSharp.ParquetFileReader..ctor(Stream stream, ReaderProperties readerProperties, Boolean leaveOpen)

Where can I get ParquetSharpNative' DLL ?

**Comment by jgiannuzzi** [comment]
Hi @milhousemanastorm, this DLL is included in the NuGet package. This kind of error usually means that there was an issue loading it.

Would you be able to tell us which kind of system your app is running on? Operating system, processor architecture, etc.?

**Comment by milhousemanastorm** [comment]
> 

The Azure Web App system is Windows 10 build 14393. 

Do I need to add
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

to my .csproj file ?

**Comment by adamreeve** [comment]
Hi @milhousemanastorm, what type of processor are you using though? If you are running on a machine with an ARM processor then that isn't currently supported by ParquetSharp on Windows. We only currently support ARM on Linux or macOS. I don't think `CopyLocalLockFileAssemblies` would help.

**Comment by milhousemanastorm** [comment]
I just ran
` Get-ChildItem 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\E*'`

and got:

PROCESSOR_ARCHITECTURE            : AMD64
NUMBER_OF_PROCESSORS              : 1           
 PROCESSOR_LEVEL                   : 6           
 PROCESSOR_IDENTIFIER              : Intel64     Family 6 Model 63 Stepping 2,     GenuineIntel
 PROCESSOR_REVISION                : 3f02

**Comment by adamreeve** [comment]
Can you verify whether ParquetSharpNative.dll is getting deployed with your application? It should be in `runtimes/win-x64/native/ParquetSharpNative.dll`.

**Comment by milhousemanastorm** [comment]
Yes it is there and the file hash is:

SHA256          C0E1574BB6DD4C182CB92EDA84BD9DE8C3DE6BD817E45F28D7E80B8724A2E37

**Comment by adamreeve** [comment]
It looks like the DLL can be found but there's an error loading it for some reason. Possibly one of the DLLs it depends on can't be loaded, although I think they're all libraries that should come with Windows. Running `dumpbin /DEPENDENTS ParquetSharpNative.dll`, I get:
* WS2_32.dll
* CRYPT32.dll
* KERNEL32.dll
* USER32.dll
* SHELL32.dll
* ole32.dll
* ADVAPI32.dll
* bcrypt.dll

You might need to use a tool like [Dependencies](https://github.com/lucasg/Dependencies) or run your application under [gflags](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags) with the "show loader snaps" option to debug what's going wrong.

**Comment by adamreeve** [comment]
I'm going to close this as I don't think we can do much more on this without further information. Please reopen this if it's still a problem and you've tried the suggestions above.

**Comment by tbeltram** [comment]
We have the same issue, and are not able to deploy parquetsharp on azure. It seems to be depending on the processor type.

**Comment by shayneoneill** [comment]
Same issue here. Has anyone had any luck diagnosing this?
