### ISSUE TITLE
How to turn off nullable operation for int double?

### ISSUE THREAD

**Issue by inie0722** [G-Research/ParquetSharp#353]
```c#
using ParquetSharp.IO;
using ParquetSharp.RowOriented;

var array = ParquetExtensions.ReadFromParquet<A>("test.parquet");
Console.WriteLine(array[0].Weight);
public static class ParquetExtensions
{
    public static T[] ReadFromParquet<T>(string file)
    {
        var array = Array.Empty<T>();
        using (var rowReader = ParquetFile.CreateRowReader<T>(file))
        {
            array = rowReader.ReadRows(0);
        }
        return array;
    }
}

public class A
{
    public string? Symbol { set; get; }
    public double Weight { set; get; }
}
```

Unhandled exception. System.InvalidCastException: Tried to get a LogicalColumnReader for column 1 ('Weight') with an element type of 'System.Double' but the actual element type is 'System.Nullable`1[System.Double]'.

**Comment by adamreeve** [comment]
Hi @inie0722, the nullability of the column is defined in the file at write time. There isn't currently a way to force reading a nullable column into a non-nullable output unless you implement a custom type mapping (https://github.com/G-Research/ParquetSharp/blob/master/docs/TypeFactories.md)
