### ISSUE TITLE
Upgrade to Arrow 12.0.1

### ISSUE THREAD

**Issue by adamreeve** [G-Research/ParquetSharp#355]
This has a fix for nullable byte stream split data (fixes #237)

**Comment by djepson** [comment]
Arrow cpp v12 also added support for writing page indexes (https://github.com/apache/arrow/pull/34054) which would close the performance gap for files I query with Spark that were created with parquet-mr vs ParquetSharp.

You would need to expose WriterProperties::enable_write_page_index() and WriterProperties::disable_write_page_index() to toggle it as it's disabled by default.

**Comment by adamreeve** [comment]
This has been released in a beta version (https://github.com/G-Research/ParquetSharp/releases/tag/12.0.1-beta1)
