### ISSUE TITLE
Question: Is there a way to write to a partitioned directory

### ISSUE THREAD

**Issue by schoetbi** [G-Research/ParquetSharp#357]
I have seen other projects that have a way to write parquet data into a directory with a partitioning scheme. E.g the python library can write parquet data like this using pandas

```
import pandas as pd

# example dataframe with 3 rows and columns year,month,day,value
df = pd.DataFrame(data={'year':  [2020, 2020, 2021],
                        'month': [1,12,2], 
                        'day':   [1,31,28], 
                        'value': [1000,2000,3000]})

df.to_parquet('./mydf', partition_cols=['year', 'month', 'day'])
```

In this case there is one directory for each of the partitioning columns.
I have not seen any unit test or mention of this type of writing in the documentation. So my question is if this is supported or should I implement this myself on top of the available api?

**Comment by adamreeve** [comment]
Hi @schoetbi, no this isn't something included in ParquetSharp, but it doesn't look like it would be too complicated to implement this using the existing API.

**Comment by adamreeve** [comment]
Closing as answered, feel free to re-open if you have any further questions

**Comment by schoetbi** [comment]
@adamreeve Sorry for answering so late, you are right, it should be easy to implement on my own. Thanks for answering.
