### ISSUE TITLE
ParquetRowWriter throws when writing a Decimal

### ISSUE THREAD

**Issue by barrypatrickdevlin** [G-Research/ParquetSharp#36]
Whenever I write Decimals with ParquetRowWriter I get an exception. 

ParquetSharp.ParquetException : class parquet::ParquetException (message: 'Invalid DECIMAL precision: -1. Precision must be a number between 1 and 38 inclusive')
   at ParquetSharp.ExceptionInfo.Check(IntPtr exceptionInfo)
   at ParquetSharp.Column.CreateSchemaNode(Type type, String name, LogicalType logicalTypeOverride, Int32 length, Int32 precision, Int32 scale)
   at ParquetSharp.ParquetFileWriter.<>c.<CreateSchema>b__8_0(Column c)

**Comment by GPSnoopy** [comment]
Creating a Decimal column requires passing some extra arguments to the schema. ParquetRowWriter should provide those when encountering a Decimal type.

**Comment by GPSnoopy** [comment]
I've added the ParquetDecimalScale attribute that can be applied on class or struct fields and properties. This does imply that System.Tuple and System.ValueTuple are not supported. Hopefully this should be enough for the moment. I don't want to spend too much time on this unless there are more use cases that need solving and we have a better picture on how to address the problem.

Done in PR #39.
