### ISSUE TITLE
[FEATURE REQUEST]: Add new tags to optimize for GitHub and Google search

### ISSUE THREAD

**Issue by jescalada** [G-Research/ParquetSharp#387]
### Is your feature request related to a problem? Please describe.

One of my goals as a DevRel fellow is to promote the project and improve its reach by using SEO techniques. After experimenting with the GitHub search engine, I've found out that tags are one of the major deciding factors for repository ranking.

These are some sample keyword searches with their respective results:
<details>
<summary>parquet</summary>

## parquet
![image](https://github.com/G-Research/ParquetSharp/assets/97265671/e02f0e25-b6e2-4322-9e5e-cfe06d5b30cb)
</details>

<details>
<summary>parquet dotnet</summary>

## parquet dotnet
![image](https://github.com/G-Research/ParquetSharp/assets/97265671/23bf93ca-510b-4c40-b762-e16a89973352)

</details>

<details>
<summary>parquet .NET</summary>

## parquet .NET
![image](https://github.com/G-Research/ParquetSharp/assets/97265671/12811b41-de45-44db-9f5b-5b0d9a76d587)

</details>

<details>
<summary>apache parquet</summary>

## apache parquet
![image](https://github.com/G-Research/ParquetSharp/assets/97265671/46ddc142-ec30-4038-93fd-d1ad90fa6ba4)

</details>

<details>
<summary>parquet csharp</summary>

## parquet csharp
![image](https://github.com/G-Research/ParquetSharp/assets/97265671/19de8771-1667-46c1-8808-f68a1c694578)

</details>

Note that of all of these queries, only "parquet .NET" returns ParquetSharp in the first page. Some of these, such as "parquet csharp" do not show it at all.

### Describe the solution you'd like

I suggest adding new tags to the repo in order to boost its ranking for the main keywords that people search for. This requires predicting which keywords are more likely to be used, as we can only have 5 tags at a time.

These are some suggested tags, obtained from similar repos (such as implementations in alternate languages):
**csharp, apache-parquet, dotnet, apache-arrow, columnar-storage, big-data**

Feel free to experiment with different tags to see which ones provide the highest overall ranking for the given keywords. I would suggest optimizing for "parquet" and "apache parquet" as they are the core relevant keywords.

**Comment by jgiannuzzi** [comment]
Thanks for your analysis @jescalada! We have added the tags you recommended 👍

**Comment by jescalada** [comment]
Thank you! :)
