### ISSUE TITLE
Illegal Parquet type: INT64 (TIMESTAMP_MICROS) error when Importing parquet in Microsoft Fabric/OneLake

### ISSUE THREAD

**Issue by CodeNinjai** [G-Research/ParquetSharp#390]
Hi,

this is basically not an issue in ParquetSharp, but I might need you help anyway. Its seems that Fabrics underlaying PySpark integration for reading parquet files doesn't handle timestamps that are presented in INT64. In fact I get an error message "Illegal Parquet type: INT64 (TIMESTAMP_MICROS)" in Fabric (I guess they use PySpark, as the error message is exactly the same as PySpark 3.2 produces).

The parquet file was written using ParquetSharp. Is there a workaround I can leverage when writing DateTime columns?

Thanks in advance,
Jan

**Comment by adamreeve** [comment]
Hi @CodeNinjai, Parquet only supports using int64 for the timestamp logical type (see https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#timestamp). I'm not familiar with Microsoft Fabric and couldn't find any documentation on this limitation from a quick search, but do you know if they support timestamps with other units, eg. milliseconds?

You can specify a different time unit by using a logical type override, eg:
```c#
var column = new Column<DateTime>("DateTime", LogicalType.Timestamp(true, TimeUnit.Millis))
```

**Comment by adamreeve** [comment]
I'm closing this as answered, but feel free to reopen if that doesn't solve the problem.
