### ISSUE TITLE
How to get column value enumerator If I don't know ahead of time the types for each column

### ISSUE THREAD

**Issue by zhengshy2016** [G-Research/ParquetSharp#395]
### Discussed in https://github.com/G-Research/ParquetSharp/discussions/394

<div type='discussions-op-text'>

<sup>Originally posted by **zhengshy2016** November 20, 2023</sup>
Hey, guy. I am trying to get the column value enumerator, but I don't know ahead of time the types of each column. Is this the correct way to get the column value enumerator? Thanks for the help.

```
var columnEnumerator = rowGroupReader.Column(0).LogicalReader().Apply(new ColumnValuesEnumerator());

sealed class ColumnValuesEnumerator : ILogicalColumnReaderVisitor<IEnumerator>
{
        public IEnumerator OnLogicalColumnReader<TElement>(LogicalColumnReader<TElement> logicalColumnReader)
        {         
            return logicalColumnReader.GetEnumerator();
        }
}
```</div>

**Comment by adamreeve** [comment]
I think this is best suited to a discussion for now so I'll close this and keep comments in the discussion.
