### ISSUE TITLE
[FEATURE REQUEST]: Support for .NET Standard 2.0

### ISSUE THREAD

**Issue by daanwissing** [G-Research/ParquetSharp#396]
### Is your feature request related to a problem? Please describe.

I have a solution with mixed .NET Framework 4.8 and .NET 6 projects. I have a class library in .NET Standard 2.0 in which I want to create a logical wrapper around ParquetSharp so it can be used in both kind of projects. However, ParquetSharp is only supported on .NET Framework 4.8 and .NET Standard 2.1 (which is not compatible with .NET Framework).

### Describe the solution you'd like

ParquetSharp is also supported for .NET Standard 2.0 projects

**Comment by adamreeve** [comment]
Hi Daan. We dropped netstandard 2.0 support in #206 to help implement proper UTF-8 support, and it looks like it would be a fair amount of work to get ParquetSharp working with netstandard 2.0.

Would it work for you if we instead added support for .NET Framework 4.8? (I think you meant to say above that ParquetSharp only supports .NET Framework 4.7.1 and .NET Standard 2.1).

**Comment by adamreeve** [comment]
Ah sorry of course, we target 4.7.1 but this will work with 4.8 too as it's backwards compatible.
