### ISSUE TITLE
[BUG]: unable to install on Windows using Nuget: The specified source 'parquetsharp.13.0.0.nupkg' is invalid.

### ISSUE THREAD

**Issue by mbourgon** [G-Research/ParquetSharp#403]
### Issue Description

I am trying to install ParquetSharp so that I can use it with Powershell. 

```nuget install ParquetSharp ```
returns: 
```Unable to find package 'ParquetSharp'```

Downloading the package from the side of the page, doesn't seem to work either:
"nuget install ParquetSharp -source parquetsharp.13.0.0.nupkg.zip -outputdirectory lib"
and received back
"The specified source 'parquetsharp.13.0.0.nupkg.zip' is invalid. Please provide a valid source."

### Environment Information

- ParquetSharp Version:  1.2.0.0
- .NET Framework/SDK Version: none - trying to get working with powershell.
- Operating System: Windows 10

### Steps To Reproduce

* Download nuget file from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
* Download parquetsharp.13.0.0.nupkg from https://www.nuget.org/packages/ParquetSharp/
* Put both in same folder
* open commandline
* run nuget install ParquetSharp -source parquetsharp.13.0.0.nupkg -outputdirectory lib
* receive error message

### Expected Behavior

package to install

### Additional Context (Optional)

Trying to not install VisualStudio. I just want to read it from powershell. Thanks!

**Comment by marcin-krystianc** [comment]
Hi @mbourgon,

I've followed your steps and it installed for me, so I'm not sure why it doesn't work for you:
```
 D:\workspace\tmp>nuget install ParquetSharp
Feeds used:
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installing package 'ParquetSharp' to 'D:\workspace\tmp'.
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/parquetsharp/index.json
Package "ParquetSharp.13.0.0" is already installed.

D:\workspace\tmp>nuget install ParquetSharp
Feeds used:
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installing package 'ParquetSharp' to 'D:\workspace\tmp'.
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/parquetsharp/index.json


Attempting to gather dependency information for package 'ParquetSharp.13.0.0' with respect to project 'D:\workspace\tmp', targeting 'Any,Version=v0.0'
Gathering dependency information took 90 ms
Attempting to resolve dependencies for package 'ParquetSharp.13.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ParquetSharp.13.0.0'
Resolved actions to install package 'ParquetSharp.13.0.0'
Found package 'Apache.Arrow 13.0.0' in 'D:\workspace\tmp'.
Retrieving package 'ParquetSharp 13.0.0' from 'nuget.org'.
Found package 'System.Buffers 4.5.1' in 'D:\workspace\tmp'.
Found package 'System.Memory 4.5.5' in 'D:\workspace\tmp'.
Found package 'System.Numerics.Vectors 4.5.0' in 'D:\workspace\tmp'.
Found package 'System.Runtime.CompilerServices.Unsafe 4.5.3' in 'D:\workspace\tmp'.
Package 'Apache.Arrow.13.0.0' already exists in folder 'D:\workspace\tmp'
Successfully installed 'Apache.Arrow 13.0.0' to D:\workspace\tmp
Package 'System.Buffers.4.5.1' already exists in folder 'D:\workspace\tmp'
Successfully installed 'System.Buffers 4.5.1' to D:\workspace\tmp
Package 'System.Numerics.Vectors.4.5.0' already exists in folder 'D:\workspace\tmp'
Successfully installed 'System.Numerics.Vectors 4.5.0' to D:\workspace\tmp
Package 'System.Runtime.CompilerServices.Unsafe.4.5.3' already exists in folder 'D:\workspace\tmp'
Successfully installed 'System.Runtime.CompilerServices.Unsafe 4.5.3' to D:\workspace\tmp
Package 'System.Memory.4.5.5' already exists in folder 'D:\workspace\tmp'
Successfully installed 'System.Memory 4.5.5' to D:\workspace\tmp
Adding package 'ParquetSharp.13.0.0' to folder 'D:\workspace\tmp'
Added package 'ParquetSharp.13.0.0' to folder 'D:\workspace\tmp'
Successfully installed 'ParquetSharp 13.0.0' to D:\workspace\tmp
Executing nuget actions took 168 ms
```

**Comment by adamreeve** [comment]
This also works fine for me. I note that in your example command you use `nuget install` but say you've downloaded nuget.exe to your working directory. Maybe powershell is running an older version of nuget from somewhere? Powershell won't usually run files from the working directory automatically. You might want to pass the path to nuget.exe explicitly, eg. `.\nuget.exe install`.

If that doesn't help, is there any other information displayed when you try to install the package? You could enable more verbose logging, eg:
```
 .\nuget.exe install ParquetSharp -OutputDirectory lib -Verbosity detailed
```

Also, the `-Source` option isn't supposed to take a path to a nupkg file but rather a URL or path for a NuGet repository. If I pass the nupkg file path as a source I get an error that "The specified source '.\parquetsharp.13.0.0.nupkg' is invalid. Please provide a valid source.". You can pass the current directory path for this option, but then NuGet will complain that it can't find other required dependencies, so you'll also need to use the main NuGet feed as a fallback. But if you can't install ParquetSharp from nuget.org you probably won't be able to install other dependencies either:

```
.\nuget.exe install ParquetSharp -Source $(Get-Location).Path -FallbackSource https://api.nuget.org/v3/index.json 
```

**Comment by mbourgon** [comment]
Thanks, y'all. Installed! Ran it from Powershell ISE and it just worked. Still throwing errors from CMD.exe, though. : ( Oh well.

What's odd is that if I run it from the standard windows cmd.exe it fails, regardless if admin. 

If I run it from powershell, it works! (and still running nuget 6.8.0.131!)

```
PS C:\users\myusername\Downloads> .\nuget.exe install ParquetSharp
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'ParquetSharp' to 'C:\users\myusername\Downloads'.
  GET https://api.nuget.org/v3/registration5-gz-semver2/parquetsharp/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/parquetsharp/index.json 163ms
```

Doing "-verbosity detailed" in cmd.exe results in this failure message, and I confirmed that it's running the same version of Nuget: 

```
C:\Users\mbourgon\Downloads>.\nuget install ParquetSharp -verbosity detailed
NuGet Version: 6.8.0.131
Feeds used:

Installing package 'ParquetSharp' to 'C:\Users\mbourgon\Downloads'.
Unable to find package 'ParquetSharp'
NuGet.Commands.CommandException: Unable to find package 'ParquetSharp'
   at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

and installing it from the downloaded pkg in cmd.exe also gives an error.

```
C:\Users\myusername\Downloads>nuget install ParquetSharp -source parquetsharp.13.0.0.nupkg -verbosity detailed
NuGet Version: 6.8.0.131
The specified source 'parquetsharp.13.0.0.nupkg' is invalid. Please provide a valid source.
NuGet.Commands.CommandException: The specified source 'parquetsharp.13.0.0.nupkg' is invalid. Please provide a valid source.
   at NuGet.CommandLine.CommandLineUtility.ValidateSource(String source)
   at NuGet.Common.PackageSourceProviderExtensions.ResolveSource(IEnumerable`1 availableSources, String source)
   at NuGet.CommandLine.DownloadCommandBase.GetPackageSources(ISettings settings)
   at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

```

So, moral of the story: cmd.exe sucks, use PoSH. Or something like that.
