### ISSUE TITLE
[FEATURE REQUEST]: LogicalWriter<> and .LogicalReader<> for object type, or the type specified at runtime

### ISSUE THREAD

**Issue by fandrei** [G-Research/ParquetSharp#406]
### Is your feature request related to a problem? Please describe.

Currently, it's
```
using var columnWriter = rowGroup.Column(c).LogicalWriter<SomeType>();
```
However, this doesn't work when the type of the column is not known during compile time, for instance when writing a list of columns with the types that aren't known in advance. Same for the reader.

### Describe the solution you'd like

```
using var columnWriter = rowGroup.Column(c).LogicalWriter<object>();
```

**Comment by adamreeve** [comment]
Hi @fandrei. Usually the way we handle this is by implementing the `ILogicalColumnWriterVisitor` interface (or `ILogicalColumnReaderVisitor` when reading data). For an example of how to do this, see [the documentation](https://github.com/G-Research/ParquetSharp/blob/master/docs/Writing.md#using-logicalcolumnwriter) or the [`LogicalValueSetter` class from our tests](https://github.com/G-Research/ParquetSharp/blob/master/csharp.test/LogicalValueSetter.cs). This implements the visitor pattern and uses the logical type as a generic type parameter.

**Comment by fandrei** [comment]
@adamreeve ok this is better. However, why don't add a helper method for this, just for consistency?

**Comment by adamreeve** [comment]
Can you give an example of what that helper method would look like and how it would work?

I'm not sure it makes sense to try to support something like the `rowGroup.Column(c).LogicalWriter<object>()` example you have above. An array of `object` could potentially contain many different types of items, so this would probably involve a lot of overhead in checking the items are all of the same type and probably copying them into a properly typed array.

**Comment by fandrei** [comment]
I really don't think that type cast would be of any importance comparing to the rest of data serialization and writing.
Think of this scenario. I need to read a file with the types of columns unknown ahead of time, modify the data and write it to another file.

**Comment by adamreeve** [comment]
I don't think that scenario makes any sense unless you know the types at some point in time though, otherwise how do you modify something if you are dealing with opaque `object` values? The visitor pattern based approach with `ILogicalColumnReaderVisitor` and `ILogicalColumnWriterVisitor` lets you access the actual type of the data and potentially handle different data types in different ways. You can probably achieve something similar by using reflection or trying type casts on the object values but that seems pretty clunky to me, and supporting this in ParquetSharp just seems like additional complexity that doesn't add much value.

**Comment by fandrei** [comment]
@adamreeve I do know, but in runtime only. But it seems that there is no way to do this without writing boilerplate code or very clumsy reflection based code?
Anyway, it's not difficult to implement having access to the internals of the library.

**Comment by adamreeve** [comment]
Right, yes the visitor implementations do seem like extra boilerplate but I would think an `object` based writer would just move that boilerplate elsewhere, as you still have to manage handling different types somehow. It's hard to say without a more realistic example though.

One other thing I should mention is you can get an untyped logical writer with `rowGroup.Column(c).LogicalWriter()` for example, and then cast that to the correct logical writer type if you know it at runtime somehow, or try casting it to different logical writer types, which might be useful in some scenarios.

**Comment by fandrei** [comment]
This example is realistic. Working only with the files that have predefined schemas, that's quite a limited approach.
Reflection or switch - yes, that would work. But it's ugly and unnecessary work for the users of this library.

**Comment by adamreeve** [comment]
Sorry I wasn't suggesting it's unrealistic to not know the schema ahead of time, I just meant that it would help to have a more complete example of how an `object` based API would work in a real use-case, and compare that to using `ILogicalColumnWriterVisitor`.

**Comment by fandrei** [comment]
@adamreeve I'd use something like this:
```
		var vals = new int[something];
		// .......
		using var writer = new ParquetFileWriter(path, columns);
		using var rowGroup = writer.AppendRowGroup();
		using var columnWriter = rowGroup.NextColumn().LogicalWriter();
		columnWriter.WriteBatch(vals);
```

**Comment by adamreeve** [comment]
In that example you know you have `int` values to write though, so you could just just use `LogicalWriter<int>`. I'm still not seeing a case where having support for `object` values would help a lot over using `ILogicalColumnWriterVisitor`. We use the visitor pattern quite successfully for situations where we don't know the schema ahead of time. Eg. we also use this in the ParquetSharp.DataFrame project: https://github.com/G-Research/ParquetSharp.DataFrame/blob/main/ParquetSharp.DataFrame/DataFrameWriter.cs

Thanks for starting this discussion but I'm going to close this as won't fix as I believe the current API is sufficient.

**Comment by fandrei** [comment]
@adamreeve  as I already said, it's simply more difficult to use than it should be.
