### ISSUE TITLE
[FEATURE REQUEST]: Strong Name

### ISSUE THREAD

**Issue by gktval** [G-Research/ParquetSharp#409]
### Is your feature request related to a problem? Please describe.

Can you strong name the assembly, please.

### Describe the solution you'd like

Many older projects in .Net Framework are strong named and require all references to be strong named as well. 

### Describe alternatives you've considered

There really is no alternative, unfortunately. Older projects that require strong naming cannot use this dependency.

**Comment by gktval** [comment]
See this was discussed already. Unfortunate.

**Comment by marcin-krystianc** [comment]
> See this was discussed already. Unfortunate.

Yeah, it is not something we can do without creating a havoc for our users -> more context here https://github.com/G-Research/ParquetSharp/pull/298/files
