### ISSUE TITLE
ParquetSharp dlls are not signed with a strong name key.

### ISSUE THREAD

**Issue by shamimashik** [G-Research/ParquetSharp#484]
### Issue Description

Is it possible to sign the dlls with a strong name key?
Ref: [https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name)

### Environment Information

- ParquetSharp Version:  any latest versions
- .NET Framework/SDK Version: [e.g. .NET Framework 4.7.2]
- Operating System: [e.g. Windows 10]

### Steps To Reproduce

// ParquetSharp.dll
// ParquetSharp, Version=16.1.0.0, Culture=neutral, PublicKeyToken=null
// Global type: <Module>
// Architecture: x64
// Runtime: v4.0.30319
// This assembly was compiled using the /deterministic option.
// Hash algorithm: SHA1

### Expected Behavior

Sign the dlls with a strong name key

**Comment by shamimashik** [comment]
@adamreeve - we had a brief chat earlier on issue [https://github.com/G-Research/ParquetSharp/issues/480](https://github.com/G-Research/ParquetSharp/issues/480)
I have verified that the release 17.0.0-beta1 is working as expected. 
Is there a way you can release a dll signed with a strong name key? Thanks.

**Comment by adamreeve** [comment]
Hi @shamimashik, this has come up previously in #298 and we decided against adding strong naming as it would be a breaking change for some applications
