### ISSUE TITLE
Update to Arrow 0.14

### ISSUE THREAD

**Issue by philjdf** [G-Research/ParquetSharp#57]
See https://github.com/microsoft/vcpkg/pull/7211 for a branch of vcpkg which builds Arrow 0.14.

**Comment by GPSnoopy** [comment]
I've spotted a bug with Arrow 0.14 that Decimal columns now have stats but the min/max values seem to be nonsensical. Need to dig into this further and report it to Arrow.

**Comment by GPSnoopy** [comment]
Merged to master with PR #58.

**Comment by GPSnoopy** [comment]
Upgraded to Arrow 0.14.1 in release 2.0.1 Beta 1.
