### ISSUE TITLE
libthrift dynamically linked

### ISSUE THREAD

**Issue by markackroyd** [G-Research/ParquetSharp#60]
ldd ParquetSharpNative.so
        linux-vdso.so.1 (0x00007ffff02f7000)
        libthrift.so.0.13.0 => not found
        libthriftz.so.0.13.0 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5702e90000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5702b00000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5702760000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5702540000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5702140000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5703800000)

**Comment by GPSnoopy** [comment]
@philjdf created this PR
https://github.com/microsoft/vcpkg/pull/7302

**Comment by GPSnoopy** [comment]
Fixed in 2.0.1-beta2 release.
