### ISSUE TITLE
PrimitiveNode.Equals() should not compare DecimalMetadata

### ISSUE THREAD

**Issue by philjdf** [G-Research/ParquetSharp#66]
The call to LogicalType.Equals() now implies comparison of the decimal data if the type is Decimal.

Also DecimalMetaData naively compares its tuple values. But in truth, if both left and right have IsSet = false, the other properties should be ignored.

**Comment by GPSnoopy** [comment]
This was highlighted by a clone of a TimeStamp node (UTC true, Micros) compared with its original. Worth writing a quick unit test.

**Comment by GPSnoopy** [comment]
As suggest by @philjdf in an IRL discussion, maybe we can just completely remove DecimalMetadata as it's made redundant by the new LogicalType implementation.

https://github.com/G-Research/ParquetSharp/search?q=DecimalMetadata&unscoped_q=DecimalMetadata

**Comment by GPSnoopy** [comment]
Fixed in 2.0.0-beta3.
