### ISSUE TITLE
Disable vcpkg debug build in CI

### ISSUE THREAD

**Issue by GPSnoopy** [G-Research/ParquetSharp#97]
Should help CI to be a bit faster. We don't actually test it anyway.

https://github.com/microsoft/vcpkg/issues/2120

**Comment by GPSnoopy** [comment]
PRs #123, #124 and #125 should alleviate the problem of build time by using of GitHub Actions cache.

However a new problem arised: disk space on these cloud instances is limited to 14GB total.

**Comment by jgiannuzzi** [comment]
vcpkg debug build cannot yet be disabled on Unix: https://github.com/microsoft/vcpkg/issues/8613

We should disable it again once this issue is solved.

**Comment by jgiannuzzi** [comment]
@GPSnoopy can we please reopen this issue?

**Comment by jgiannuzzi** [comment]
Commented on this PR to get things moving on vcpkg: https://github.com/microsoft/vcpkg/pull/9224#issuecomment-621215431

**Comment by jgiannuzzi** [comment]
Submitted new PR as per maintainer's request: https://github.com/microsoft/vcpkg/pull/11098

**Comment by GPSnoopy** [comment]
https://github.com/microsoft/vcpkg/pull/9224 has now been merged. Waiting for master to point to a working version of vcpkg (master or tagged branch).

**Comment by GPSnoopy** [comment]
But Windows is now broken because of https://github.com/microsoft/vcpkg/issues/12799

![Kitten Whack-a-Mole](https://media2.giphy.com/media/MVUyVpyjakkRW/giphy.gif)

**Comment by GPSnoopy** [comment]
Not sure we want to complete this. It's been very useful to have ParquetSharp CI test vcpkg Arrow ports in both Debug and Release. Ideally we'd want to keep Windows Debug too; but it's just too slow and disk space hungry. I think we can afford to keep the Debug release on the UNIX path. GitHub Actions cache has been helping a lot already in not having to rebuild vcpkg dependencies all the time.
